// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"context"

	"github.com/go-tangra/go-tangra-notification/internal/data/ent/channel"
	"github.com/go-tangra/go-tangra-notification/internal/data/ent/notificationlog"
	"github.com/go-tangra/go-tangra-notification/internal/data/ent/schema"
	"github.com/go-tangra/go-tangra-notification/internal/data/ent/template"
	"github.com/go-tangra/go-tangra-notification/internal/data/ent/templatepermission"

	"entgo.io/ent"
	"entgo.io/ent/privacy"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	channelMixin := schema.Channel{}.Mixin()
	channel.Policy = privacy.NewPolicies(channelMixin[3], schema.Channel{})
	channel.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := channel.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	channelMixinFields3 := channelMixin[3].Fields()
	_ = channelMixinFields3
	channelFields := schema.Channel{}.Fields()
	_ = channelFields
	// channelDescTenantID is the schema descriptor for tenant_id field.
	channelDescTenantID := channelMixinFields3[0].Descriptor()
	// channel.DefaultTenantID holds the default value on creation for the tenant_id field.
	channel.DefaultTenantID = channelDescTenantID.Default.(uint32)
	// channelDescName is the schema descriptor for name field.
	channelDescName := channelFields[1].Descriptor()
	// channel.NameValidator is a validator for the "name" field. It is called by the builders before save.
	channel.NameValidator = func() func(string) error {
		validators := channelDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// channelDescConfig is the schema descriptor for config field.
	channelDescConfig := channelFields[3].Descriptor()
	// channel.DefaultConfig holds the default value on creation for the config field.
	channel.DefaultConfig = channelDescConfig.Default.(string)
	// channelDescEnabled is the schema descriptor for enabled field.
	channelDescEnabled := channelFields[4].Descriptor()
	// channel.DefaultEnabled holds the default value on creation for the enabled field.
	channel.DefaultEnabled = channelDescEnabled.Default.(bool)
	// channelDescIsDefault is the schema descriptor for is_default field.
	channelDescIsDefault := channelFields[5].Descriptor()
	// channel.DefaultIsDefault holds the default value on creation for the is_default field.
	channel.DefaultIsDefault = channelDescIsDefault.Default.(bool)
	// channelDescID is the schema descriptor for id field.
	channelDescID := channelFields[0].Descriptor()
	// channel.IDValidator is a validator for the "id" field. It is called by the builders before save.
	channel.IDValidator = channelDescID.Validators[0].(func(string) error)
	notificationlogMixin := schema.NotificationLog{}.Mixin()
	notificationlog.Policy = privacy.NewPolicies(notificationlogMixin[2], schema.NotificationLog{})
	notificationlog.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := notificationlog.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	notificationlogMixinFields2 := notificationlogMixin[2].Fields()
	_ = notificationlogMixinFields2
	notificationlogFields := schema.NotificationLog{}.Fields()
	_ = notificationlogFields
	// notificationlogDescTenantID is the schema descriptor for tenant_id field.
	notificationlogDescTenantID := notificationlogMixinFields2[0].Descriptor()
	// notificationlog.DefaultTenantID holds the default value on creation for the tenant_id field.
	notificationlog.DefaultTenantID = notificationlogDescTenantID.Default.(uint32)
	// notificationlogDescChannelID is the schema descriptor for channel_id field.
	notificationlogDescChannelID := notificationlogFields[1].Descriptor()
	// notificationlog.ChannelIDValidator is a validator for the "channel_id" field. It is called by the builders before save.
	notificationlog.ChannelIDValidator = func() func(string) error {
		validators := notificationlogDescChannelID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(channel_id string) error {
			for _, fn := range fns {
				if err := fn(channel_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// notificationlogDescTemplateID is the schema descriptor for template_id field.
	notificationlogDescTemplateID := notificationlogFields[3].Descriptor()
	// notificationlog.TemplateIDValidator is a validator for the "template_id" field. It is called by the builders before save.
	notificationlog.TemplateIDValidator = func() func(string) error {
		validators := notificationlogDescTemplateID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(template_id string) error {
			for _, fn := range fns {
				if err := fn(template_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// notificationlogDescRecipient is the schema descriptor for recipient field.
	notificationlogDescRecipient := notificationlogFields[4].Descriptor()
	// notificationlog.RecipientValidator is a validator for the "recipient" field. It is called by the builders before save.
	notificationlog.RecipientValidator = func() func(string) error {
		validators := notificationlogDescRecipient.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(recipient string) error {
			for _, fn := range fns {
				if err := fn(recipient); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// notificationlogDescRenderedSubject is the schema descriptor for rendered_subject field.
	notificationlogDescRenderedSubject := notificationlogFields[5].Descriptor()
	// notificationlog.DefaultRenderedSubject holds the default value on creation for the rendered_subject field.
	notificationlog.DefaultRenderedSubject = notificationlogDescRenderedSubject.Default.(string)
	// notificationlog.RenderedSubjectValidator is a validator for the "rendered_subject" field. It is called by the builders before save.
	notificationlog.RenderedSubjectValidator = notificationlogDescRenderedSubject.Validators[0].(func(string) error)
	// notificationlogDescRenderedBody is the schema descriptor for rendered_body field.
	notificationlogDescRenderedBody := notificationlogFields[6].Descriptor()
	// notificationlog.DefaultRenderedBody holds the default value on creation for the rendered_body field.
	notificationlog.DefaultRenderedBody = notificationlogDescRenderedBody.Default.(string)
	// notificationlogDescErrorMessage is the schema descriptor for error_message field.
	notificationlogDescErrorMessage := notificationlogFields[8].Descriptor()
	// notificationlog.DefaultErrorMessage holds the default value on creation for the error_message field.
	notificationlog.DefaultErrorMessage = notificationlogDescErrorMessage.Default.(string)
	// notificationlogDescID is the schema descriptor for id field.
	notificationlogDescID := notificationlogFields[0].Descriptor()
	// notificationlog.IDValidator is a validator for the "id" field. It is called by the builders before save.
	notificationlog.IDValidator = notificationlogDescID.Validators[0].(func(string) error)
	templateMixin := schema.Template{}.Mixin()
	template.Policy = privacy.NewPolicies(templateMixin[3], schema.Template{})
	template.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := template.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	templateMixinFields3 := templateMixin[3].Fields()
	_ = templateMixinFields3
	templateFields := schema.Template{}.Fields()
	_ = templateFields
	// templateDescTenantID is the schema descriptor for tenant_id field.
	templateDescTenantID := templateMixinFields3[0].Descriptor()
	// template.DefaultTenantID holds the default value on creation for the tenant_id field.
	template.DefaultTenantID = templateDescTenantID.Default.(uint32)
	// templateDescName is the schema descriptor for name field.
	templateDescName := templateFields[1].Descriptor()
	// template.NameValidator is a validator for the "name" field. It is called by the builders before save.
	template.NameValidator = func() func(string) error {
		validators := templateDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// templateDescChannelID is the schema descriptor for channel_id field.
	templateDescChannelID := templateFields[2].Descriptor()
	// template.ChannelIDValidator is a validator for the "channel_id" field. It is called by the builders before save.
	template.ChannelIDValidator = func() func(string) error {
		validators := templateDescChannelID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(channel_id string) error {
			for _, fn := range fns {
				if err := fn(channel_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// templateDescSubject is the schema descriptor for subject field.
	templateDescSubject := templateFields[3].Descriptor()
	// template.SubjectValidator is a validator for the "subject" field. It is called by the builders before save.
	template.SubjectValidator = func() func(string) error {
		validators := templateDescSubject.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(subject string) error {
			for _, fn := range fns {
				if err := fn(subject); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// templateDescBody is the schema descriptor for body field.
	templateDescBody := templateFields[4].Descriptor()
	// template.BodyValidator is a validator for the "body" field. It is called by the builders before save.
	template.BodyValidator = templateDescBody.Validators[0].(func(string) error)
	// templateDescVariables is the schema descriptor for variables field.
	templateDescVariables := templateFields[5].Descriptor()
	// template.DefaultVariables holds the default value on creation for the variables field.
	template.DefaultVariables = templateDescVariables.Default.(string)
	// template.VariablesValidator is a validator for the "variables" field. It is called by the builders before save.
	template.VariablesValidator = templateDescVariables.Validators[0].(func(string) error)
	// templateDescIsDefault is the schema descriptor for is_default field.
	templateDescIsDefault := templateFields[6].Descriptor()
	// template.DefaultIsDefault holds the default value on creation for the is_default field.
	template.DefaultIsDefault = templateDescIsDefault.Default.(bool)
	// templateDescID is the schema descriptor for id field.
	templateDescID := templateFields[0].Descriptor()
	// template.IDValidator is a validator for the "id" field. It is called by the builders before save.
	template.IDValidator = templateDescID.Validators[0].(func(string) error)
	templatepermissionMixin := schema.TemplatePermission{}.Mixin()
	templatepermission.Policy = privacy.NewPolicies(templatepermissionMixin[1], schema.TemplatePermission{})
	templatepermission.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := templatepermission.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	templatepermissionMixinFields1 := templatepermissionMixin[1].Fields()
	_ = templatepermissionMixinFields1
	templatepermissionFields := schema.TemplatePermission{}.Fields()
	_ = templatepermissionFields
	// templatepermissionDescTenantID is the schema descriptor for tenant_id field.
	templatepermissionDescTenantID := templatepermissionMixinFields1[0].Descriptor()
	// templatepermission.DefaultTenantID holds the default value on creation for the tenant_id field.
	templatepermission.DefaultTenantID = templatepermissionDescTenantID.Default.(uint32)
	// templatepermissionDescResourceID is the schema descriptor for resource_id field.
	templatepermissionDescResourceID := templatepermissionFields[1].Descriptor()
	// templatepermission.ResourceIDValidator is a validator for the "resource_id" field. It is called by the builders before save.
	templatepermission.ResourceIDValidator = func() func(string) error {
		validators := templatepermissionDescResourceID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(resource_id string) error {
			for _, fn := range fns {
				if err := fn(resource_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// templatepermissionDescSubjectID is the schema descriptor for subject_id field.
	templatepermissionDescSubjectID := templatepermissionFields[4].Descriptor()
	// templatepermission.SubjectIDValidator is a validator for the "subject_id" field. It is called by the builders before save.
	templatepermission.SubjectIDValidator = func() func(string) error {
		validators := templatepermissionDescSubjectID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(subject_id string) error {
			for _, fn := range fns {
				if err := fn(subject_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
}

const (
	Version = "v0.14.5"                                         // Version of ent codegen.
	Sum     = "h1:Rj2WOYJtCkWyFo6a+5wB3EfBRP0rnx1fMk6gGA0UUe4=" // Sum of ent codegen.
)
