// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-notification/internal/data/ent/channel"
	"github.com/go-tangra/go-tangra-notification/internal/data/ent/predicate"
)

// ChannelUpdate is the builder for updating Channel entities.
type ChannelUpdate struct {
	config
	hooks     []Hook
	mutation  *ChannelMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ChannelUpdate builder.
func (_u *ChannelUpdate) Where(ps ...predicate.Channel) *ChannelUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreateBy sets the "create_by" field.
func (_u *ChannelUpdate) SetCreateBy(v uint32) *ChannelUpdate {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *ChannelUpdate) SetNillableCreateBy(v *uint32) *ChannelUpdate {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *ChannelUpdate) AddCreateBy(v int32) *ChannelUpdate {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *ChannelUpdate) ClearCreateBy() *ChannelUpdate {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateBy sets the "update_by" field.
func (_u *ChannelUpdate) SetUpdateBy(v uint32) *ChannelUpdate {
	_u.mutation.ResetUpdateBy()
	_u.mutation.SetUpdateBy(v)
	return _u
}

// SetNillableUpdateBy sets the "update_by" field if the given value is not nil.
func (_u *ChannelUpdate) SetNillableUpdateBy(v *uint32) *ChannelUpdate {
	if v != nil {
		_u.SetUpdateBy(*v)
	}
	return _u
}

// AddUpdateBy adds value to the "update_by" field.
func (_u *ChannelUpdate) AddUpdateBy(v int32) *ChannelUpdate {
	_u.mutation.AddUpdateBy(v)
	return _u
}

// ClearUpdateBy clears the value of the "update_by" field.
func (_u *ChannelUpdate) ClearUpdateBy() *ChannelUpdate {
	_u.mutation.ClearUpdateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *ChannelUpdate) SetUpdateTime(v time.Time) *ChannelUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *ChannelUpdate) SetNillableUpdateTime(v *time.Time) *ChannelUpdate {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *ChannelUpdate) ClearUpdateTime() *ChannelUpdate {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *ChannelUpdate) SetDeleteTime(v time.Time) *ChannelUpdate {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *ChannelUpdate) SetNillableDeleteTime(v *time.Time) *ChannelUpdate {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *ChannelUpdate) ClearDeleteTime() *ChannelUpdate {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetName sets the "name" field.
func (_u *ChannelUpdate) SetName(v string) *ChannelUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ChannelUpdate) SetNillableName(v *string) *ChannelUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *ChannelUpdate) SetType(v channel.Type) *ChannelUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *ChannelUpdate) SetNillableType(v *channel.Type) *ChannelUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetConfig sets the "config" field.
func (_u *ChannelUpdate) SetConfig(v string) *ChannelUpdate {
	_u.mutation.SetConfig(v)
	return _u
}

// SetNillableConfig sets the "config" field if the given value is not nil.
func (_u *ChannelUpdate) SetNillableConfig(v *string) *ChannelUpdate {
	if v != nil {
		_u.SetConfig(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ChannelUpdate) SetEnabled(v bool) *ChannelUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ChannelUpdate) SetNillableEnabled(v *bool) *ChannelUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetIsDefault sets the "is_default" field.
func (_u *ChannelUpdate) SetIsDefault(v bool) *ChannelUpdate {
	_u.mutation.SetIsDefault(v)
	return _u
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_u *ChannelUpdate) SetNillableIsDefault(v *bool) *ChannelUpdate {
	if v != nil {
		_u.SetIsDefault(*v)
	}
	return _u
}

// Mutation returns the ChannelMutation object of the builder.
func (_u *ChannelUpdate) Mutation() *ChannelMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChannelUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChannelUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChannelUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChannelUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChannelUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := channel.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Channel.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := channel.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Channel.type": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ChannelUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ChannelUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ChannelUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(channel.Table, channel.Columns, sqlgraph.NewFieldSpec(channel.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(channel.FieldCreateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(channel.FieldCreateBy, field.TypeUint32, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(channel.FieldCreateBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdateBy(); ok {
		_spec.SetField(channel.FieldUpdateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdateBy(); ok {
		_spec.AddField(channel.FieldUpdateBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdateByCleared() {
		_spec.ClearField(channel.FieldUpdateBy, field.TypeUint32)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(channel.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(channel.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(channel.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(channel.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(channel.FieldDeleteTime, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(channel.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(channel.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(channel.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(channel.FieldConfig, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(channel.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsDefault(); ok {
		_spec.SetField(channel.FieldIsDefault, field.TypeBool, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{channel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChannelUpdateOne is the builder for updating a single Channel entity.
type ChannelUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ChannelMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetCreateBy sets the "create_by" field.
func (_u *ChannelUpdateOne) SetCreateBy(v uint32) *ChannelUpdateOne {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *ChannelUpdateOne) SetNillableCreateBy(v *uint32) *ChannelUpdateOne {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *ChannelUpdateOne) AddCreateBy(v int32) *ChannelUpdateOne {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *ChannelUpdateOne) ClearCreateBy() *ChannelUpdateOne {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateBy sets the "update_by" field.
func (_u *ChannelUpdateOne) SetUpdateBy(v uint32) *ChannelUpdateOne {
	_u.mutation.ResetUpdateBy()
	_u.mutation.SetUpdateBy(v)
	return _u
}

// SetNillableUpdateBy sets the "update_by" field if the given value is not nil.
func (_u *ChannelUpdateOne) SetNillableUpdateBy(v *uint32) *ChannelUpdateOne {
	if v != nil {
		_u.SetUpdateBy(*v)
	}
	return _u
}

// AddUpdateBy adds value to the "update_by" field.
func (_u *ChannelUpdateOne) AddUpdateBy(v int32) *ChannelUpdateOne {
	_u.mutation.AddUpdateBy(v)
	return _u
}

// ClearUpdateBy clears the value of the "update_by" field.
func (_u *ChannelUpdateOne) ClearUpdateBy() *ChannelUpdateOne {
	_u.mutation.ClearUpdateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *ChannelUpdateOne) SetUpdateTime(v time.Time) *ChannelUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *ChannelUpdateOne) SetNillableUpdateTime(v *time.Time) *ChannelUpdateOne {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *ChannelUpdateOne) ClearUpdateTime() *ChannelUpdateOne {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *ChannelUpdateOne) SetDeleteTime(v time.Time) *ChannelUpdateOne {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *ChannelUpdateOne) SetNillableDeleteTime(v *time.Time) *ChannelUpdateOne {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *ChannelUpdateOne) ClearDeleteTime() *ChannelUpdateOne {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetName sets the "name" field.
func (_u *ChannelUpdateOne) SetName(v string) *ChannelUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ChannelUpdateOne) SetNillableName(v *string) *ChannelUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *ChannelUpdateOne) SetType(v channel.Type) *ChannelUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *ChannelUpdateOne) SetNillableType(v *channel.Type) *ChannelUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetConfig sets the "config" field.
func (_u *ChannelUpdateOne) SetConfig(v string) *ChannelUpdateOne {
	_u.mutation.SetConfig(v)
	return _u
}

// SetNillableConfig sets the "config" field if the given value is not nil.
func (_u *ChannelUpdateOne) SetNillableConfig(v *string) *ChannelUpdateOne {
	if v != nil {
		_u.SetConfig(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ChannelUpdateOne) SetEnabled(v bool) *ChannelUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ChannelUpdateOne) SetNillableEnabled(v *bool) *ChannelUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetIsDefault sets the "is_default" field.
func (_u *ChannelUpdateOne) SetIsDefault(v bool) *ChannelUpdateOne {
	_u.mutation.SetIsDefault(v)
	return _u
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_u *ChannelUpdateOne) SetNillableIsDefault(v *bool) *ChannelUpdateOne {
	if v != nil {
		_u.SetIsDefault(*v)
	}
	return _u
}

// Mutation returns the ChannelMutation object of the builder.
func (_u *ChannelUpdateOne) Mutation() *ChannelMutation {
	return _u.mutation
}

// Where appends a list predicates to the ChannelUpdate builder.
func (_u *ChannelUpdateOne) Where(ps ...predicate.Channel) *ChannelUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChannelUpdateOne) Select(field string, fields ...string) *ChannelUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Channel entity.
func (_u *ChannelUpdateOne) Save(ctx context.Context) (*Channel, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChannelUpdateOne) SaveX(ctx context.Context) *Channel {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChannelUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChannelUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChannelUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := channel.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Channel.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := channel.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Channel.type": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ChannelUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ChannelUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ChannelUpdateOne) sqlSave(ctx context.Context) (_node *Channel, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(channel.Table, channel.Columns, sqlgraph.NewFieldSpec(channel.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Channel.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, channel.FieldID)
		for _, f := range fields {
			if !channel.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != channel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(channel.FieldCreateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(channel.FieldCreateBy, field.TypeUint32, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(channel.FieldCreateBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdateBy(); ok {
		_spec.SetField(channel.FieldUpdateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdateBy(); ok {
		_spec.AddField(channel.FieldUpdateBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdateByCleared() {
		_spec.ClearField(channel.FieldUpdateBy, field.TypeUint32)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(channel.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(channel.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(channel.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(channel.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(channel.FieldDeleteTime, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(channel.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(channel.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(channel.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(channel.FieldConfig, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(channel.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsDefault(); ok {
		_spec.SetField(channel.FieldIsDefault, field.TypeBool, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Channel{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{channel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
