// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/go-tangra/go-tangra-notification/internal/data/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/go-tangra/go-tangra-notification/internal/data/ent/channel"
	"github.com/go-tangra/go-tangra-notification/internal/data/ent/internalmessage"
	"github.com/go-tangra/go-tangra-notification/internal/data/ent/internalmessagecategory"
	"github.com/go-tangra/go-tangra-notification/internal/data/ent/internalmessagerecipient"
	"github.com/go-tangra/go-tangra-notification/internal/data/ent/notificationlog"
	"github.com/go-tangra/go-tangra-notification/internal/data/ent/template"
	"github.com/go-tangra/go-tangra-notification/internal/data/ent/templatepermission"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Channel is the client for interacting with the Channel builders.
	Channel *ChannelClient
	// InternalMessage is the client for interacting with the InternalMessage builders.
	InternalMessage *InternalMessageClient
	// InternalMessageCategory is the client for interacting with the InternalMessageCategory builders.
	InternalMessageCategory *InternalMessageCategoryClient
	// InternalMessageRecipient is the client for interacting with the InternalMessageRecipient builders.
	InternalMessageRecipient *InternalMessageRecipientClient
	// NotificationLog is the client for interacting with the NotificationLog builders.
	NotificationLog *NotificationLogClient
	// Template is the client for interacting with the Template builders.
	Template *TemplateClient
	// TemplatePermission is the client for interacting with the TemplatePermission builders.
	TemplatePermission *TemplatePermissionClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Channel = NewChannelClient(c.config)
	c.InternalMessage = NewInternalMessageClient(c.config)
	c.InternalMessageCategory = NewInternalMessageCategoryClient(c.config)
	c.InternalMessageRecipient = NewInternalMessageRecipientClient(c.config)
	c.NotificationLog = NewNotificationLogClient(c.config)
	c.Template = NewTemplateClient(c.config)
	c.TemplatePermission = NewTemplatePermissionClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                      ctx,
		config:                   cfg,
		Channel:                  NewChannelClient(cfg),
		InternalMessage:          NewInternalMessageClient(cfg),
		InternalMessageCategory:  NewInternalMessageCategoryClient(cfg),
		InternalMessageRecipient: NewInternalMessageRecipientClient(cfg),
		NotificationLog:          NewNotificationLogClient(cfg),
		Template:                 NewTemplateClient(cfg),
		TemplatePermission:       NewTemplatePermissionClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                      ctx,
		config:                   cfg,
		Channel:                  NewChannelClient(cfg),
		InternalMessage:          NewInternalMessageClient(cfg),
		InternalMessageCategory:  NewInternalMessageCategoryClient(cfg),
		InternalMessageRecipient: NewInternalMessageRecipientClient(cfg),
		NotificationLog:          NewNotificationLogClient(cfg),
		Template:                 NewTemplateClient(cfg),
		TemplatePermission:       NewTemplatePermissionClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Channel.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.Channel, c.InternalMessage, c.InternalMessageCategory,
		c.InternalMessageRecipient, c.NotificationLog, c.Template,
		c.TemplatePermission,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.Channel, c.InternalMessage, c.InternalMessageCategory,
		c.InternalMessageRecipient, c.NotificationLog, c.Template,
		c.TemplatePermission,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *ChannelMutation:
		return c.Channel.mutate(ctx, m)
	case *InternalMessageMutation:
		return c.InternalMessage.mutate(ctx, m)
	case *InternalMessageCategoryMutation:
		return c.InternalMessageCategory.mutate(ctx, m)
	case *InternalMessageRecipientMutation:
		return c.InternalMessageRecipient.mutate(ctx, m)
	case *NotificationLogMutation:
		return c.NotificationLog.mutate(ctx, m)
	case *TemplateMutation:
		return c.Template.mutate(ctx, m)
	case *TemplatePermissionMutation:
		return c.TemplatePermission.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// ChannelClient is a client for the Channel schema.
type ChannelClient struct {
	config
}

// NewChannelClient returns a client for the Channel from the given config.
func NewChannelClient(c config) *ChannelClient {
	return &ChannelClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `channel.Hooks(f(g(h())))`.
func (c *ChannelClient) Use(hooks ...Hook) {
	c.hooks.Channel = append(c.hooks.Channel, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `channel.Intercept(f(g(h())))`.
func (c *ChannelClient) Intercept(interceptors ...Interceptor) {
	c.inters.Channel = append(c.inters.Channel, interceptors...)
}

// Create returns a builder for creating a Channel entity.
func (c *ChannelClient) Create() *ChannelCreate {
	mutation := newChannelMutation(c.config, OpCreate)
	return &ChannelCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Channel entities.
func (c *ChannelClient) CreateBulk(builders ...*ChannelCreate) *ChannelCreateBulk {
	return &ChannelCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ChannelClient) MapCreateBulk(slice any, setFunc func(*ChannelCreate, int)) *ChannelCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ChannelCreateBulk{err: fmt.Errorf("calling to ChannelClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ChannelCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ChannelCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Channel.
func (c *ChannelClient) Update() *ChannelUpdate {
	mutation := newChannelMutation(c.config, OpUpdate)
	return &ChannelUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ChannelClient) UpdateOne(_m *Channel) *ChannelUpdateOne {
	mutation := newChannelMutation(c.config, OpUpdateOne, withChannel(_m))
	return &ChannelUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ChannelClient) UpdateOneID(id string) *ChannelUpdateOne {
	mutation := newChannelMutation(c.config, OpUpdateOne, withChannelID(id))
	return &ChannelUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Channel.
func (c *ChannelClient) Delete() *ChannelDelete {
	mutation := newChannelMutation(c.config, OpDelete)
	return &ChannelDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ChannelClient) DeleteOne(_m *Channel) *ChannelDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ChannelClient) DeleteOneID(id string) *ChannelDeleteOne {
	builder := c.Delete().Where(channel.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ChannelDeleteOne{builder}
}

// Query returns a query builder for Channel.
func (c *ChannelClient) Query() *ChannelQuery {
	return &ChannelQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeChannel},
		inters: c.Interceptors(),
	}
}

// Get returns a Channel entity by its id.
func (c *ChannelClient) Get(ctx context.Context, id string) (*Channel, error) {
	return c.Query().Where(channel.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ChannelClient) GetX(ctx context.Context, id string) *Channel {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ChannelClient) Hooks() []Hook {
	hooks := c.hooks.Channel
	return append(hooks[:len(hooks):len(hooks)], channel.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *ChannelClient) Interceptors() []Interceptor {
	return c.inters.Channel
}

func (c *ChannelClient) mutate(ctx context.Context, m *ChannelMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ChannelCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ChannelUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ChannelUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ChannelDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Channel mutation op: %q", m.Op())
	}
}

// InternalMessageClient is a client for the InternalMessage schema.
type InternalMessageClient struct {
	config
}

// NewInternalMessageClient returns a client for the InternalMessage from the given config.
func NewInternalMessageClient(c config) *InternalMessageClient {
	return &InternalMessageClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `internalmessage.Hooks(f(g(h())))`.
func (c *InternalMessageClient) Use(hooks ...Hook) {
	c.hooks.InternalMessage = append(c.hooks.InternalMessage, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `internalmessage.Intercept(f(g(h())))`.
func (c *InternalMessageClient) Intercept(interceptors ...Interceptor) {
	c.inters.InternalMessage = append(c.inters.InternalMessage, interceptors...)
}

// Create returns a builder for creating a InternalMessage entity.
func (c *InternalMessageClient) Create() *InternalMessageCreate {
	mutation := newInternalMessageMutation(c.config, OpCreate)
	return &InternalMessageCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of InternalMessage entities.
func (c *InternalMessageClient) CreateBulk(builders ...*InternalMessageCreate) *InternalMessageCreateBulk {
	return &InternalMessageCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *InternalMessageClient) MapCreateBulk(slice any, setFunc func(*InternalMessageCreate, int)) *InternalMessageCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &InternalMessageCreateBulk{err: fmt.Errorf("calling to InternalMessageClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*InternalMessageCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &InternalMessageCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for InternalMessage.
func (c *InternalMessageClient) Update() *InternalMessageUpdate {
	mutation := newInternalMessageMutation(c.config, OpUpdate)
	return &InternalMessageUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *InternalMessageClient) UpdateOne(_m *InternalMessage) *InternalMessageUpdateOne {
	mutation := newInternalMessageMutation(c.config, OpUpdateOne, withInternalMessage(_m))
	return &InternalMessageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *InternalMessageClient) UpdateOneID(id uint32) *InternalMessageUpdateOne {
	mutation := newInternalMessageMutation(c.config, OpUpdateOne, withInternalMessageID(id))
	return &InternalMessageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for InternalMessage.
func (c *InternalMessageClient) Delete() *InternalMessageDelete {
	mutation := newInternalMessageMutation(c.config, OpDelete)
	return &InternalMessageDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *InternalMessageClient) DeleteOne(_m *InternalMessage) *InternalMessageDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *InternalMessageClient) DeleteOneID(id uint32) *InternalMessageDeleteOne {
	builder := c.Delete().Where(internalmessage.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &InternalMessageDeleteOne{builder}
}

// Query returns a query builder for InternalMessage.
func (c *InternalMessageClient) Query() *InternalMessageQuery {
	return &InternalMessageQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeInternalMessage},
		inters: c.Interceptors(),
	}
}

// Get returns a InternalMessage entity by its id.
func (c *InternalMessageClient) Get(ctx context.Context, id uint32) (*InternalMessage, error) {
	return c.Query().Where(internalmessage.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *InternalMessageClient) GetX(ctx context.Context, id uint32) *InternalMessage {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *InternalMessageClient) Hooks() []Hook {
	hooks := c.hooks.InternalMessage
	return append(hooks[:len(hooks):len(hooks)], internalmessage.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *InternalMessageClient) Interceptors() []Interceptor {
	return c.inters.InternalMessage
}

func (c *InternalMessageClient) mutate(ctx context.Context, m *InternalMessageMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&InternalMessageCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&InternalMessageUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&InternalMessageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&InternalMessageDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown InternalMessage mutation op: %q", m.Op())
	}
}

// InternalMessageCategoryClient is a client for the InternalMessageCategory schema.
type InternalMessageCategoryClient struct {
	config
}

// NewInternalMessageCategoryClient returns a client for the InternalMessageCategory from the given config.
func NewInternalMessageCategoryClient(c config) *InternalMessageCategoryClient {
	return &InternalMessageCategoryClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `internalmessagecategory.Hooks(f(g(h())))`.
func (c *InternalMessageCategoryClient) Use(hooks ...Hook) {
	c.hooks.InternalMessageCategory = append(c.hooks.InternalMessageCategory, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `internalmessagecategory.Intercept(f(g(h())))`.
func (c *InternalMessageCategoryClient) Intercept(interceptors ...Interceptor) {
	c.inters.InternalMessageCategory = append(c.inters.InternalMessageCategory, interceptors...)
}

// Create returns a builder for creating a InternalMessageCategory entity.
func (c *InternalMessageCategoryClient) Create() *InternalMessageCategoryCreate {
	mutation := newInternalMessageCategoryMutation(c.config, OpCreate)
	return &InternalMessageCategoryCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of InternalMessageCategory entities.
func (c *InternalMessageCategoryClient) CreateBulk(builders ...*InternalMessageCategoryCreate) *InternalMessageCategoryCreateBulk {
	return &InternalMessageCategoryCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *InternalMessageCategoryClient) MapCreateBulk(slice any, setFunc func(*InternalMessageCategoryCreate, int)) *InternalMessageCategoryCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &InternalMessageCategoryCreateBulk{err: fmt.Errorf("calling to InternalMessageCategoryClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*InternalMessageCategoryCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &InternalMessageCategoryCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for InternalMessageCategory.
func (c *InternalMessageCategoryClient) Update() *InternalMessageCategoryUpdate {
	mutation := newInternalMessageCategoryMutation(c.config, OpUpdate)
	return &InternalMessageCategoryUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *InternalMessageCategoryClient) UpdateOne(_m *InternalMessageCategory) *InternalMessageCategoryUpdateOne {
	mutation := newInternalMessageCategoryMutation(c.config, OpUpdateOne, withInternalMessageCategory(_m))
	return &InternalMessageCategoryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *InternalMessageCategoryClient) UpdateOneID(id uint32) *InternalMessageCategoryUpdateOne {
	mutation := newInternalMessageCategoryMutation(c.config, OpUpdateOne, withInternalMessageCategoryID(id))
	return &InternalMessageCategoryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for InternalMessageCategory.
func (c *InternalMessageCategoryClient) Delete() *InternalMessageCategoryDelete {
	mutation := newInternalMessageCategoryMutation(c.config, OpDelete)
	return &InternalMessageCategoryDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *InternalMessageCategoryClient) DeleteOne(_m *InternalMessageCategory) *InternalMessageCategoryDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *InternalMessageCategoryClient) DeleteOneID(id uint32) *InternalMessageCategoryDeleteOne {
	builder := c.Delete().Where(internalmessagecategory.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &InternalMessageCategoryDeleteOne{builder}
}

// Query returns a query builder for InternalMessageCategory.
func (c *InternalMessageCategoryClient) Query() *InternalMessageCategoryQuery {
	return &InternalMessageCategoryQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeInternalMessageCategory},
		inters: c.Interceptors(),
	}
}

// Get returns a InternalMessageCategory entity by its id.
func (c *InternalMessageCategoryClient) Get(ctx context.Context, id uint32) (*InternalMessageCategory, error) {
	return c.Query().Where(internalmessagecategory.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *InternalMessageCategoryClient) GetX(ctx context.Context, id uint32) *InternalMessageCategory {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *InternalMessageCategoryClient) Hooks() []Hook {
	hooks := c.hooks.InternalMessageCategory
	return append(hooks[:len(hooks):len(hooks)], internalmessagecategory.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *InternalMessageCategoryClient) Interceptors() []Interceptor {
	return c.inters.InternalMessageCategory
}

func (c *InternalMessageCategoryClient) mutate(ctx context.Context, m *InternalMessageCategoryMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&InternalMessageCategoryCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&InternalMessageCategoryUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&InternalMessageCategoryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&InternalMessageCategoryDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown InternalMessageCategory mutation op: %q", m.Op())
	}
}

// InternalMessageRecipientClient is a client for the InternalMessageRecipient schema.
type InternalMessageRecipientClient struct {
	config
}

// NewInternalMessageRecipientClient returns a client for the InternalMessageRecipient from the given config.
func NewInternalMessageRecipientClient(c config) *InternalMessageRecipientClient {
	return &InternalMessageRecipientClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `internalmessagerecipient.Hooks(f(g(h())))`.
func (c *InternalMessageRecipientClient) Use(hooks ...Hook) {
	c.hooks.InternalMessageRecipient = append(c.hooks.InternalMessageRecipient, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `internalmessagerecipient.Intercept(f(g(h())))`.
func (c *InternalMessageRecipientClient) Intercept(interceptors ...Interceptor) {
	c.inters.InternalMessageRecipient = append(c.inters.InternalMessageRecipient, interceptors...)
}

// Create returns a builder for creating a InternalMessageRecipient entity.
func (c *InternalMessageRecipientClient) Create() *InternalMessageRecipientCreate {
	mutation := newInternalMessageRecipientMutation(c.config, OpCreate)
	return &InternalMessageRecipientCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of InternalMessageRecipient entities.
func (c *InternalMessageRecipientClient) CreateBulk(builders ...*InternalMessageRecipientCreate) *InternalMessageRecipientCreateBulk {
	return &InternalMessageRecipientCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *InternalMessageRecipientClient) MapCreateBulk(slice any, setFunc func(*InternalMessageRecipientCreate, int)) *InternalMessageRecipientCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &InternalMessageRecipientCreateBulk{err: fmt.Errorf("calling to InternalMessageRecipientClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*InternalMessageRecipientCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &InternalMessageRecipientCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for InternalMessageRecipient.
func (c *InternalMessageRecipientClient) Update() *InternalMessageRecipientUpdate {
	mutation := newInternalMessageRecipientMutation(c.config, OpUpdate)
	return &InternalMessageRecipientUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *InternalMessageRecipientClient) UpdateOne(_m *InternalMessageRecipient) *InternalMessageRecipientUpdateOne {
	mutation := newInternalMessageRecipientMutation(c.config, OpUpdateOne, withInternalMessageRecipient(_m))
	return &InternalMessageRecipientUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *InternalMessageRecipientClient) UpdateOneID(id uint32) *InternalMessageRecipientUpdateOne {
	mutation := newInternalMessageRecipientMutation(c.config, OpUpdateOne, withInternalMessageRecipientID(id))
	return &InternalMessageRecipientUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for InternalMessageRecipient.
func (c *InternalMessageRecipientClient) Delete() *InternalMessageRecipientDelete {
	mutation := newInternalMessageRecipientMutation(c.config, OpDelete)
	return &InternalMessageRecipientDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *InternalMessageRecipientClient) DeleteOne(_m *InternalMessageRecipient) *InternalMessageRecipientDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *InternalMessageRecipientClient) DeleteOneID(id uint32) *InternalMessageRecipientDeleteOne {
	builder := c.Delete().Where(internalmessagerecipient.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &InternalMessageRecipientDeleteOne{builder}
}

// Query returns a query builder for InternalMessageRecipient.
func (c *InternalMessageRecipientClient) Query() *InternalMessageRecipientQuery {
	return &InternalMessageRecipientQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeInternalMessageRecipient},
		inters: c.Interceptors(),
	}
}

// Get returns a InternalMessageRecipient entity by its id.
func (c *InternalMessageRecipientClient) Get(ctx context.Context, id uint32) (*InternalMessageRecipient, error) {
	return c.Query().Where(internalmessagerecipient.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *InternalMessageRecipientClient) GetX(ctx context.Context, id uint32) *InternalMessageRecipient {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *InternalMessageRecipientClient) Hooks() []Hook {
	hooks := c.hooks.InternalMessageRecipient
	return append(hooks[:len(hooks):len(hooks)], internalmessagerecipient.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *InternalMessageRecipientClient) Interceptors() []Interceptor {
	return c.inters.InternalMessageRecipient
}

func (c *InternalMessageRecipientClient) mutate(ctx context.Context, m *InternalMessageRecipientMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&InternalMessageRecipientCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&InternalMessageRecipientUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&InternalMessageRecipientUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&InternalMessageRecipientDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown InternalMessageRecipient mutation op: %q", m.Op())
	}
}

// NotificationLogClient is a client for the NotificationLog schema.
type NotificationLogClient struct {
	config
}

// NewNotificationLogClient returns a client for the NotificationLog from the given config.
func NewNotificationLogClient(c config) *NotificationLogClient {
	return &NotificationLogClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `notificationlog.Hooks(f(g(h())))`.
func (c *NotificationLogClient) Use(hooks ...Hook) {
	c.hooks.NotificationLog = append(c.hooks.NotificationLog, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `notificationlog.Intercept(f(g(h())))`.
func (c *NotificationLogClient) Intercept(interceptors ...Interceptor) {
	c.inters.NotificationLog = append(c.inters.NotificationLog, interceptors...)
}

// Create returns a builder for creating a NotificationLog entity.
func (c *NotificationLogClient) Create() *NotificationLogCreate {
	mutation := newNotificationLogMutation(c.config, OpCreate)
	return &NotificationLogCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of NotificationLog entities.
func (c *NotificationLogClient) CreateBulk(builders ...*NotificationLogCreate) *NotificationLogCreateBulk {
	return &NotificationLogCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *NotificationLogClient) MapCreateBulk(slice any, setFunc func(*NotificationLogCreate, int)) *NotificationLogCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &NotificationLogCreateBulk{err: fmt.Errorf("calling to NotificationLogClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*NotificationLogCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &NotificationLogCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for NotificationLog.
func (c *NotificationLogClient) Update() *NotificationLogUpdate {
	mutation := newNotificationLogMutation(c.config, OpUpdate)
	return &NotificationLogUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *NotificationLogClient) UpdateOne(_m *NotificationLog) *NotificationLogUpdateOne {
	mutation := newNotificationLogMutation(c.config, OpUpdateOne, withNotificationLog(_m))
	return &NotificationLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *NotificationLogClient) UpdateOneID(id string) *NotificationLogUpdateOne {
	mutation := newNotificationLogMutation(c.config, OpUpdateOne, withNotificationLogID(id))
	return &NotificationLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for NotificationLog.
func (c *NotificationLogClient) Delete() *NotificationLogDelete {
	mutation := newNotificationLogMutation(c.config, OpDelete)
	return &NotificationLogDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *NotificationLogClient) DeleteOne(_m *NotificationLog) *NotificationLogDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *NotificationLogClient) DeleteOneID(id string) *NotificationLogDeleteOne {
	builder := c.Delete().Where(notificationlog.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &NotificationLogDeleteOne{builder}
}

// Query returns a query builder for NotificationLog.
func (c *NotificationLogClient) Query() *NotificationLogQuery {
	return &NotificationLogQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeNotificationLog},
		inters: c.Interceptors(),
	}
}

// Get returns a NotificationLog entity by its id.
func (c *NotificationLogClient) Get(ctx context.Context, id string) (*NotificationLog, error) {
	return c.Query().Where(notificationlog.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *NotificationLogClient) GetX(ctx context.Context, id string) *NotificationLog {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *NotificationLogClient) Hooks() []Hook {
	hooks := c.hooks.NotificationLog
	return append(hooks[:len(hooks):len(hooks)], notificationlog.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *NotificationLogClient) Interceptors() []Interceptor {
	return c.inters.NotificationLog
}

func (c *NotificationLogClient) mutate(ctx context.Context, m *NotificationLogMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&NotificationLogCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&NotificationLogUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&NotificationLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&NotificationLogDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown NotificationLog mutation op: %q", m.Op())
	}
}

// TemplateClient is a client for the Template schema.
type TemplateClient struct {
	config
}

// NewTemplateClient returns a client for the Template from the given config.
func NewTemplateClient(c config) *TemplateClient {
	return &TemplateClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `template.Hooks(f(g(h())))`.
func (c *TemplateClient) Use(hooks ...Hook) {
	c.hooks.Template = append(c.hooks.Template, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `template.Intercept(f(g(h())))`.
func (c *TemplateClient) Intercept(interceptors ...Interceptor) {
	c.inters.Template = append(c.inters.Template, interceptors...)
}

// Create returns a builder for creating a Template entity.
func (c *TemplateClient) Create() *TemplateCreate {
	mutation := newTemplateMutation(c.config, OpCreate)
	return &TemplateCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Template entities.
func (c *TemplateClient) CreateBulk(builders ...*TemplateCreate) *TemplateCreateBulk {
	return &TemplateCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TemplateClient) MapCreateBulk(slice any, setFunc func(*TemplateCreate, int)) *TemplateCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TemplateCreateBulk{err: fmt.Errorf("calling to TemplateClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TemplateCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TemplateCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Template.
func (c *TemplateClient) Update() *TemplateUpdate {
	mutation := newTemplateMutation(c.config, OpUpdate)
	return &TemplateUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TemplateClient) UpdateOne(_m *Template) *TemplateUpdateOne {
	mutation := newTemplateMutation(c.config, OpUpdateOne, withTemplate(_m))
	return &TemplateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TemplateClient) UpdateOneID(id string) *TemplateUpdateOne {
	mutation := newTemplateMutation(c.config, OpUpdateOne, withTemplateID(id))
	return &TemplateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Template.
func (c *TemplateClient) Delete() *TemplateDelete {
	mutation := newTemplateMutation(c.config, OpDelete)
	return &TemplateDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TemplateClient) DeleteOne(_m *Template) *TemplateDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TemplateClient) DeleteOneID(id string) *TemplateDeleteOne {
	builder := c.Delete().Where(template.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TemplateDeleteOne{builder}
}

// Query returns a query builder for Template.
func (c *TemplateClient) Query() *TemplateQuery {
	return &TemplateQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTemplate},
		inters: c.Interceptors(),
	}
}

// Get returns a Template entity by its id.
func (c *TemplateClient) Get(ctx context.Context, id string) (*Template, error) {
	return c.Query().Where(template.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TemplateClient) GetX(ctx context.Context, id string) *Template {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *TemplateClient) Hooks() []Hook {
	hooks := c.hooks.Template
	return append(hooks[:len(hooks):len(hooks)], template.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *TemplateClient) Interceptors() []Interceptor {
	return c.inters.Template
}

func (c *TemplateClient) mutate(ctx context.Context, m *TemplateMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TemplateCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TemplateUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TemplateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TemplateDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Template mutation op: %q", m.Op())
	}
}

// TemplatePermissionClient is a client for the TemplatePermission schema.
type TemplatePermissionClient struct {
	config
}

// NewTemplatePermissionClient returns a client for the TemplatePermission from the given config.
func NewTemplatePermissionClient(c config) *TemplatePermissionClient {
	return &TemplatePermissionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `templatepermission.Hooks(f(g(h())))`.
func (c *TemplatePermissionClient) Use(hooks ...Hook) {
	c.hooks.TemplatePermission = append(c.hooks.TemplatePermission, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `templatepermission.Intercept(f(g(h())))`.
func (c *TemplatePermissionClient) Intercept(interceptors ...Interceptor) {
	c.inters.TemplatePermission = append(c.inters.TemplatePermission, interceptors...)
}

// Create returns a builder for creating a TemplatePermission entity.
func (c *TemplatePermissionClient) Create() *TemplatePermissionCreate {
	mutation := newTemplatePermissionMutation(c.config, OpCreate)
	return &TemplatePermissionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of TemplatePermission entities.
func (c *TemplatePermissionClient) CreateBulk(builders ...*TemplatePermissionCreate) *TemplatePermissionCreateBulk {
	return &TemplatePermissionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TemplatePermissionClient) MapCreateBulk(slice any, setFunc func(*TemplatePermissionCreate, int)) *TemplatePermissionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TemplatePermissionCreateBulk{err: fmt.Errorf("calling to TemplatePermissionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TemplatePermissionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TemplatePermissionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for TemplatePermission.
func (c *TemplatePermissionClient) Update() *TemplatePermissionUpdate {
	mutation := newTemplatePermissionMutation(c.config, OpUpdate)
	return &TemplatePermissionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TemplatePermissionClient) UpdateOne(_m *TemplatePermission) *TemplatePermissionUpdateOne {
	mutation := newTemplatePermissionMutation(c.config, OpUpdateOne, withTemplatePermission(_m))
	return &TemplatePermissionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TemplatePermissionClient) UpdateOneID(id int) *TemplatePermissionUpdateOne {
	mutation := newTemplatePermissionMutation(c.config, OpUpdateOne, withTemplatePermissionID(id))
	return &TemplatePermissionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for TemplatePermission.
func (c *TemplatePermissionClient) Delete() *TemplatePermissionDelete {
	mutation := newTemplatePermissionMutation(c.config, OpDelete)
	return &TemplatePermissionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TemplatePermissionClient) DeleteOne(_m *TemplatePermission) *TemplatePermissionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TemplatePermissionClient) DeleteOneID(id int) *TemplatePermissionDeleteOne {
	builder := c.Delete().Where(templatepermission.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TemplatePermissionDeleteOne{builder}
}

// Query returns a query builder for TemplatePermission.
func (c *TemplatePermissionClient) Query() *TemplatePermissionQuery {
	return &TemplatePermissionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTemplatePermission},
		inters: c.Interceptors(),
	}
}

// Get returns a TemplatePermission entity by its id.
func (c *TemplatePermissionClient) Get(ctx context.Context, id int) (*TemplatePermission, error) {
	return c.Query().Where(templatepermission.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TemplatePermissionClient) GetX(ctx context.Context, id int) *TemplatePermission {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *TemplatePermissionClient) Hooks() []Hook {
	hooks := c.hooks.TemplatePermission
	return append(hooks[:len(hooks):len(hooks)], templatepermission.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *TemplatePermissionClient) Interceptors() []Interceptor {
	return c.inters.TemplatePermission
}

func (c *TemplatePermissionClient) mutate(ctx context.Context, m *TemplatePermissionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TemplatePermissionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TemplatePermissionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TemplatePermissionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TemplatePermissionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown TemplatePermission mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Channel, InternalMessage, InternalMessageCategory, InternalMessageRecipient,
		NotificationLog, Template, TemplatePermission []ent.Hook
	}
	inters struct {
		Channel, InternalMessage, InternalMessageCategory, InternalMessageRecipient,
		NotificationLog, Template, TemplatePermission []ent.Interceptor
	}
)
