// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/go-tangra/go-tangra-notification/internal/data/ent/notificationlog"
)

// NotificationLog is the model entity for the NotificationLog schema.
type NotificationLog struct {
	config `json:"-"`
	// ID of the ent.
	// UUID primary key
	ID string `json:"id,omitempty"`
	// 创建者ID
	CreateBy *uint32 `json:"create_by,omitempty"`
	// 创建时间
	CreateTime *time.Time `json:"create_time,omitempty"`
	// 更新时间
	UpdateTime *time.Time `json:"update_time,omitempty"`
	// 删除时间
	DeleteTime *time.Time `json:"delete_time,omitempty"`
	// 租户ID
	TenantID *uint32 `json:"tenant_id,omitempty"`
	// FK to notification_channels
	ChannelID string `json:"channel_id,omitempty"`
	// Channel type used
	ChannelType notificationlog.ChannelType `json:"channel_type,omitempty"`
	// FK to notification_templates
	TemplateID string `json:"template_id,omitempty"`
	// Recipient address
	Recipient string `json:"recipient,omitempty"`
	// Rendered subject
	RenderedSubject string `json:"rendered_subject,omitempty"`
	// Rendered body
	RenderedBody string `json:"rendered_body,omitempty"`
	// Delivery status
	Status notificationlog.Status `json:"status,omitempty"`
	// Error message if delivery failed
	ErrorMessage string `json:"error_message,omitempty"`
	// When the notification was sent
	SentAt       *time.Time `json:"sent_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*NotificationLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case notificationlog.FieldCreateBy, notificationlog.FieldTenantID:
			values[i] = new(sql.NullInt64)
		case notificationlog.FieldID, notificationlog.FieldChannelID, notificationlog.FieldChannelType, notificationlog.FieldTemplateID, notificationlog.FieldRecipient, notificationlog.FieldRenderedSubject, notificationlog.FieldRenderedBody, notificationlog.FieldStatus, notificationlog.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case notificationlog.FieldCreateTime, notificationlog.FieldUpdateTime, notificationlog.FieldDeleteTime, notificationlog.FieldSentAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the NotificationLog fields.
func (_m *NotificationLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case notificationlog.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case notificationlog.FieldCreateBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field create_by", values[i])
			} else if value.Valid {
				_m.CreateBy = new(uint32)
				*_m.CreateBy = uint32(value.Int64)
			}
		case notificationlog.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = new(time.Time)
				*_m.CreateTime = value.Time
			}
		case notificationlog.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = new(time.Time)
				*_m.UpdateTime = value.Time
			}
		case notificationlog.FieldDeleteTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field delete_time", values[i])
			} else if value.Valid {
				_m.DeleteTime = new(time.Time)
				*_m.DeleteTime = value.Time
			}
		case notificationlog.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = new(uint32)
				*_m.TenantID = uint32(value.Int64)
			}
		case notificationlog.FieldChannelID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field channel_id", values[i])
			} else if value.Valid {
				_m.ChannelID = value.String
			}
		case notificationlog.FieldChannelType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field channel_type", values[i])
			} else if value.Valid {
				_m.ChannelType = notificationlog.ChannelType(value.String)
			}
		case notificationlog.FieldTemplateID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field template_id", values[i])
			} else if value.Valid {
				_m.TemplateID = value.String
			}
		case notificationlog.FieldRecipient:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field recipient", values[i])
			} else if value.Valid {
				_m.Recipient = value.String
			}
		case notificationlog.FieldRenderedSubject:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rendered_subject", values[i])
			} else if value.Valid {
				_m.RenderedSubject = value.String
			}
		case notificationlog.FieldRenderedBody:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rendered_body", values[i])
			} else if value.Valid {
				_m.RenderedBody = value.String
			}
		case notificationlog.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = notificationlog.Status(value.String)
			}
		case notificationlog.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = value.String
			}
		case notificationlog.FieldSentAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field sent_at", values[i])
			} else if value.Valid {
				_m.SentAt = new(time.Time)
				*_m.SentAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the NotificationLog.
// This includes values selected through modifiers, order, etc.
func (_m *NotificationLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this NotificationLog.
// Note that you need to call NotificationLog.Unwrap() before calling this method if this NotificationLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *NotificationLog) Update() *NotificationLogUpdateOne {
	return NewNotificationLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the NotificationLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *NotificationLog) Unwrap() *NotificationLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: NotificationLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *NotificationLog) String() string {
	var builder strings.Builder
	builder.WriteString("NotificationLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.CreateBy; v != nil {
		builder.WriteString("create_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CreateTime; v != nil {
		builder.WriteString("create_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdateTime; v != nil {
		builder.WriteString("update_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DeleteTime; v != nil {
		builder.WriteString("delete_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.TenantID; v != nil {
		builder.WriteString("tenant_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("channel_id=")
	builder.WriteString(_m.ChannelID)
	builder.WriteString(", ")
	builder.WriteString("channel_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChannelType))
	builder.WriteString(", ")
	builder.WriteString("template_id=")
	builder.WriteString(_m.TemplateID)
	builder.WriteString(", ")
	builder.WriteString("recipient=")
	builder.WriteString(_m.Recipient)
	builder.WriteString(", ")
	builder.WriteString("rendered_subject=")
	builder.WriteString(_m.RenderedSubject)
	builder.WriteString(", ")
	builder.WriteString("rendered_body=")
	builder.WriteString(_m.RenderedBody)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("error_message=")
	builder.WriteString(_m.ErrorMessage)
	builder.WriteString(", ")
	if v := _m.SentAt; v != nil {
		builder.WriteString("sent_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// NotificationLogs is a parsable slice of NotificationLog.
type NotificationLogs []*NotificationLog
