// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-notification/internal/data/ent/notificationlog"
	"github.com/go-tangra/go-tangra-notification/internal/data/ent/predicate"
)

// NotificationLogUpdate is the builder for updating NotificationLog entities.
type NotificationLogUpdate struct {
	config
	hooks     []Hook
	mutation  *NotificationLogMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the NotificationLogUpdate builder.
func (_u *NotificationLogUpdate) Where(ps ...predicate.NotificationLog) *NotificationLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreateBy sets the "create_by" field.
func (_u *NotificationLogUpdate) SetCreateBy(v uint32) *NotificationLogUpdate {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *NotificationLogUpdate) SetNillableCreateBy(v *uint32) *NotificationLogUpdate {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *NotificationLogUpdate) AddCreateBy(v int32) *NotificationLogUpdate {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *NotificationLogUpdate) ClearCreateBy() *NotificationLogUpdate {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *NotificationLogUpdate) SetUpdateTime(v time.Time) *NotificationLogUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *NotificationLogUpdate) SetNillableUpdateTime(v *time.Time) *NotificationLogUpdate {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *NotificationLogUpdate) ClearUpdateTime() *NotificationLogUpdate {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *NotificationLogUpdate) SetDeleteTime(v time.Time) *NotificationLogUpdate {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *NotificationLogUpdate) SetNillableDeleteTime(v *time.Time) *NotificationLogUpdate {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *NotificationLogUpdate) ClearDeleteTime() *NotificationLogUpdate {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *NotificationLogUpdate) SetChannelID(v string) *NotificationLogUpdate {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *NotificationLogUpdate) SetNillableChannelID(v *string) *NotificationLogUpdate {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// SetChannelType sets the "channel_type" field.
func (_u *NotificationLogUpdate) SetChannelType(v notificationlog.ChannelType) *NotificationLogUpdate {
	_u.mutation.SetChannelType(v)
	return _u
}

// SetNillableChannelType sets the "channel_type" field if the given value is not nil.
func (_u *NotificationLogUpdate) SetNillableChannelType(v *notificationlog.ChannelType) *NotificationLogUpdate {
	if v != nil {
		_u.SetChannelType(*v)
	}
	return _u
}

// SetTemplateID sets the "template_id" field.
func (_u *NotificationLogUpdate) SetTemplateID(v string) *NotificationLogUpdate {
	_u.mutation.SetTemplateID(v)
	return _u
}

// SetNillableTemplateID sets the "template_id" field if the given value is not nil.
func (_u *NotificationLogUpdate) SetNillableTemplateID(v *string) *NotificationLogUpdate {
	if v != nil {
		_u.SetTemplateID(*v)
	}
	return _u
}

// SetRecipient sets the "recipient" field.
func (_u *NotificationLogUpdate) SetRecipient(v string) *NotificationLogUpdate {
	_u.mutation.SetRecipient(v)
	return _u
}

// SetNillableRecipient sets the "recipient" field if the given value is not nil.
func (_u *NotificationLogUpdate) SetNillableRecipient(v *string) *NotificationLogUpdate {
	if v != nil {
		_u.SetRecipient(*v)
	}
	return _u
}

// SetRenderedSubject sets the "rendered_subject" field.
func (_u *NotificationLogUpdate) SetRenderedSubject(v string) *NotificationLogUpdate {
	_u.mutation.SetRenderedSubject(v)
	return _u
}

// SetNillableRenderedSubject sets the "rendered_subject" field if the given value is not nil.
func (_u *NotificationLogUpdate) SetNillableRenderedSubject(v *string) *NotificationLogUpdate {
	if v != nil {
		_u.SetRenderedSubject(*v)
	}
	return _u
}

// SetRenderedBody sets the "rendered_body" field.
func (_u *NotificationLogUpdate) SetRenderedBody(v string) *NotificationLogUpdate {
	_u.mutation.SetRenderedBody(v)
	return _u
}

// SetNillableRenderedBody sets the "rendered_body" field if the given value is not nil.
func (_u *NotificationLogUpdate) SetNillableRenderedBody(v *string) *NotificationLogUpdate {
	if v != nil {
		_u.SetRenderedBody(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *NotificationLogUpdate) SetStatus(v notificationlog.Status) *NotificationLogUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *NotificationLogUpdate) SetNillableStatus(v *notificationlog.Status) *NotificationLogUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *NotificationLogUpdate) SetErrorMessage(v string) *NotificationLogUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *NotificationLogUpdate) SetNillableErrorMessage(v *string) *NotificationLogUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// SetSentAt sets the "sent_at" field.
func (_u *NotificationLogUpdate) SetSentAt(v time.Time) *NotificationLogUpdate {
	_u.mutation.SetSentAt(v)
	return _u
}

// SetNillableSentAt sets the "sent_at" field if the given value is not nil.
func (_u *NotificationLogUpdate) SetNillableSentAt(v *time.Time) *NotificationLogUpdate {
	if v != nil {
		_u.SetSentAt(*v)
	}
	return _u
}

// ClearSentAt clears the value of the "sent_at" field.
func (_u *NotificationLogUpdate) ClearSentAt() *NotificationLogUpdate {
	_u.mutation.ClearSentAt()
	return _u
}

// Mutation returns the NotificationLogMutation object of the builder.
func (_u *NotificationLogUpdate) Mutation() *NotificationLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NotificationLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NotificationLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotificationLogUpdate) check() error {
	if v, ok := _u.mutation.ChannelID(); ok {
		if err := notificationlog.ChannelIDValidator(v); err != nil {
			return &ValidationError{Name: "channel_id", err: fmt.Errorf(`ent: validator failed for field "NotificationLog.channel_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChannelType(); ok {
		if err := notificationlog.ChannelTypeValidator(v); err != nil {
			return &ValidationError{Name: "channel_type", err: fmt.Errorf(`ent: validator failed for field "NotificationLog.channel_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TemplateID(); ok {
		if err := notificationlog.TemplateIDValidator(v); err != nil {
			return &ValidationError{Name: "template_id", err: fmt.Errorf(`ent: validator failed for field "NotificationLog.template_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Recipient(); ok {
		if err := notificationlog.RecipientValidator(v); err != nil {
			return &ValidationError{Name: "recipient", err: fmt.Errorf(`ent: validator failed for field "NotificationLog.recipient": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RenderedSubject(); ok {
		if err := notificationlog.RenderedSubjectValidator(v); err != nil {
			return &ValidationError{Name: "rendered_subject", err: fmt.Errorf(`ent: validator failed for field "NotificationLog.rendered_subject": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := notificationlog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "NotificationLog.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *NotificationLogUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *NotificationLogUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *NotificationLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notificationlog.Table, notificationlog.Columns, sqlgraph.NewFieldSpec(notificationlog.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(notificationlog.FieldCreateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(notificationlog.FieldCreateBy, field.TypeUint32, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(notificationlog.FieldCreateBy, field.TypeUint32)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(notificationlog.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(notificationlog.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(notificationlog.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(notificationlog.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(notificationlog.FieldDeleteTime, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(notificationlog.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.ChannelID(); ok {
		_spec.SetField(notificationlog.FieldChannelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChannelType(); ok {
		_spec.SetField(notificationlog.FieldChannelType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TemplateID(); ok {
		_spec.SetField(notificationlog.FieldTemplateID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Recipient(); ok {
		_spec.SetField(notificationlog.FieldRecipient, field.TypeString, value)
	}
	if value, ok := _u.mutation.RenderedSubject(); ok {
		_spec.SetField(notificationlog.FieldRenderedSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.RenderedBody(); ok {
		_spec.SetField(notificationlog.FieldRenderedBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(notificationlog.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(notificationlog.FieldErrorMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.SentAt(); ok {
		_spec.SetField(notificationlog.FieldSentAt, field.TypeTime, value)
	}
	if _u.mutation.SentAtCleared() {
		_spec.ClearField(notificationlog.FieldSentAt, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notificationlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NotificationLogUpdateOne is the builder for updating a single NotificationLog entity.
type NotificationLogUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *NotificationLogMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetCreateBy sets the "create_by" field.
func (_u *NotificationLogUpdateOne) SetCreateBy(v uint32) *NotificationLogUpdateOne {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *NotificationLogUpdateOne) SetNillableCreateBy(v *uint32) *NotificationLogUpdateOne {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *NotificationLogUpdateOne) AddCreateBy(v int32) *NotificationLogUpdateOne {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *NotificationLogUpdateOne) ClearCreateBy() *NotificationLogUpdateOne {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *NotificationLogUpdateOne) SetUpdateTime(v time.Time) *NotificationLogUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *NotificationLogUpdateOne) SetNillableUpdateTime(v *time.Time) *NotificationLogUpdateOne {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *NotificationLogUpdateOne) ClearUpdateTime() *NotificationLogUpdateOne {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *NotificationLogUpdateOne) SetDeleteTime(v time.Time) *NotificationLogUpdateOne {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *NotificationLogUpdateOne) SetNillableDeleteTime(v *time.Time) *NotificationLogUpdateOne {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *NotificationLogUpdateOne) ClearDeleteTime() *NotificationLogUpdateOne {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *NotificationLogUpdateOne) SetChannelID(v string) *NotificationLogUpdateOne {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *NotificationLogUpdateOne) SetNillableChannelID(v *string) *NotificationLogUpdateOne {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// SetChannelType sets the "channel_type" field.
func (_u *NotificationLogUpdateOne) SetChannelType(v notificationlog.ChannelType) *NotificationLogUpdateOne {
	_u.mutation.SetChannelType(v)
	return _u
}

// SetNillableChannelType sets the "channel_type" field if the given value is not nil.
func (_u *NotificationLogUpdateOne) SetNillableChannelType(v *notificationlog.ChannelType) *NotificationLogUpdateOne {
	if v != nil {
		_u.SetChannelType(*v)
	}
	return _u
}

// SetTemplateID sets the "template_id" field.
func (_u *NotificationLogUpdateOne) SetTemplateID(v string) *NotificationLogUpdateOne {
	_u.mutation.SetTemplateID(v)
	return _u
}

// SetNillableTemplateID sets the "template_id" field if the given value is not nil.
func (_u *NotificationLogUpdateOne) SetNillableTemplateID(v *string) *NotificationLogUpdateOne {
	if v != nil {
		_u.SetTemplateID(*v)
	}
	return _u
}

// SetRecipient sets the "recipient" field.
func (_u *NotificationLogUpdateOne) SetRecipient(v string) *NotificationLogUpdateOne {
	_u.mutation.SetRecipient(v)
	return _u
}

// SetNillableRecipient sets the "recipient" field if the given value is not nil.
func (_u *NotificationLogUpdateOne) SetNillableRecipient(v *string) *NotificationLogUpdateOne {
	if v != nil {
		_u.SetRecipient(*v)
	}
	return _u
}

// SetRenderedSubject sets the "rendered_subject" field.
func (_u *NotificationLogUpdateOne) SetRenderedSubject(v string) *NotificationLogUpdateOne {
	_u.mutation.SetRenderedSubject(v)
	return _u
}

// SetNillableRenderedSubject sets the "rendered_subject" field if the given value is not nil.
func (_u *NotificationLogUpdateOne) SetNillableRenderedSubject(v *string) *NotificationLogUpdateOne {
	if v != nil {
		_u.SetRenderedSubject(*v)
	}
	return _u
}

// SetRenderedBody sets the "rendered_body" field.
func (_u *NotificationLogUpdateOne) SetRenderedBody(v string) *NotificationLogUpdateOne {
	_u.mutation.SetRenderedBody(v)
	return _u
}

// SetNillableRenderedBody sets the "rendered_body" field if the given value is not nil.
func (_u *NotificationLogUpdateOne) SetNillableRenderedBody(v *string) *NotificationLogUpdateOne {
	if v != nil {
		_u.SetRenderedBody(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *NotificationLogUpdateOne) SetStatus(v notificationlog.Status) *NotificationLogUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *NotificationLogUpdateOne) SetNillableStatus(v *notificationlog.Status) *NotificationLogUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *NotificationLogUpdateOne) SetErrorMessage(v string) *NotificationLogUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *NotificationLogUpdateOne) SetNillableErrorMessage(v *string) *NotificationLogUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// SetSentAt sets the "sent_at" field.
func (_u *NotificationLogUpdateOne) SetSentAt(v time.Time) *NotificationLogUpdateOne {
	_u.mutation.SetSentAt(v)
	return _u
}

// SetNillableSentAt sets the "sent_at" field if the given value is not nil.
func (_u *NotificationLogUpdateOne) SetNillableSentAt(v *time.Time) *NotificationLogUpdateOne {
	if v != nil {
		_u.SetSentAt(*v)
	}
	return _u
}

// ClearSentAt clears the value of the "sent_at" field.
func (_u *NotificationLogUpdateOne) ClearSentAt() *NotificationLogUpdateOne {
	_u.mutation.ClearSentAt()
	return _u
}

// Mutation returns the NotificationLogMutation object of the builder.
func (_u *NotificationLogUpdateOne) Mutation() *NotificationLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the NotificationLogUpdate builder.
func (_u *NotificationLogUpdateOne) Where(ps ...predicate.NotificationLog) *NotificationLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NotificationLogUpdateOne) Select(field string, fields ...string) *NotificationLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated NotificationLog entity.
func (_u *NotificationLogUpdateOne) Save(ctx context.Context) (*NotificationLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationLogUpdateOne) SaveX(ctx context.Context) *NotificationLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NotificationLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotificationLogUpdateOne) check() error {
	if v, ok := _u.mutation.ChannelID(); ok {
		if err := notificationlog.ChannelIDValidator(v); err != nil {
			return &ValidationError{Name: "channel_id", err: fmt.Errorf(`ent: validator failed for field "NotificationLog.channel_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChannelType(); ok {
		if err := notificationlog.ChannelTypeValidator(v); err != nil {
			return &ValidationError{Name: "channel_type", err: fmt.Errorf(`ent: validator failed for field "NotificationLog.channel_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TemplateID(); ok {
		if err := notificationlog.TemplateIDValidator(v); err != nil {
			return &ValidationError{Name: "template_id", err: fmt.Errorf(`ent: validator failed for field "NotificationLog.template_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Recipient(); ok {
		if err := notificationlog.RecipientValidator(v); err != nil {
			return &ValidationError{Name: "recipient", err: fmt.Errorf(`ent: validator failed for field "NotificationLog.recipient": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RenderedSubject(); ok {
		if err := notificationlog.RenderedSubjectValidator(v); err != nil {
			return &ValidationError{Name: "rendered_subject", err: fmt.Errorf(`ent: validator failed for field "NotificationLog.rendered_subject": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := notificationlog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "NotificationLog.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *NotificationLogUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *NotificationLogUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *NotificationLogUpdateOne) sqlSave(ctx context.Context) (_node *NotificationLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notificationlog.Table, notificationlog.Columns, sqlgraph.NewFieldSpec(notificationlog.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "NotificationLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notificationlog.FieldID)
		for _, f := range fields {
			if !notificationlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != notificationlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(notificationlog.FieldCreateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(notificationlog.FieldCreateBy, field.TypeUint32, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(notificationlog.FieldCreateBy, field.TypeUint32)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(notificationlog.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(notificationlog.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(notificationlog.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(notificationlog.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(notificationlog.FieldDeleteTime, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(notificationlog.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.ChannelID(); ok {
		_spec.SetField(notificationlog.FieldChannelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChannelType(); ok {
		_spec.SetField(notificationlog.FieldChannelType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TemplateID(); ok {
		_spec.SetField(notificationlog.FieldTemplateID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Recipient(); ok {
		_spec.SetField(notificationlog.FieldRecipient, field.TypeString, value)
	}
	if value, ok := _u.mutation.RenderedSubject(); ok {
		_spec.SetField(notificationlog.FieldRenderedSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.RenderedBody(); ok {
		_spec.SetField(notificationlog.FieldRenderedBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(notificationlog.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(notificationlog.FieldErrorMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.SentAt(); ok {
		_spec.SetField(notificationlog.FieldSentAt, field.TypeTime, value)
	}
	if _u.mutation.SentAtCleared() {
		_spec.ClearField(notificationlog.FieldSentAt, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &NotificationLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notificationlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
