// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-notification/internal/data/ent/notificationlog"
)

// NotificationLogCreate is the builder for creating a NotificationLog entity.
type NotificationLogCreate struct {
	config
	mutation *NotificationLogMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateBy sets the "create_by" field.
func (_c *NotificationLogCreate) SetCreateBy(v uint32) *NotificationLogCreate {
	_c.mutation.SetCreateBy(v)
	return _c
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_c *NotificationLogCreate) SetNillableCreateBy(v *uint32) *NotificationLogCreate {
	if v != nil {
		_c.SetCreateBy(*v)
	}
	return _c
}

// SetCreateTime sets the "create_time" field.
func (_c *NotificationLogCreate) SetCreateTime(v time.Time) *NotificationLogCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *NotificationLogCreate) SetNillableCreateTime(v *time.Time) *NotificationLogCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *NotificationLogCreate) SetUpdateTime(v time.Time) *NotificationLogCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *NotificationLogCreate) SetNillableUpdateTime(v *time.Time) *NotificationLogCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetDeleteTime sets the "delete_time" field.
func (_c *NotificationLogCreate) SetDeleteTime(v time.Time) *NotificationLogCreate {
	_c.mutation.SetDeleteTime(v)
	return _c
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_c *NotificationLogCreate) SetNillableDeleteTime(v *time.Time) *NotificationLogCreate {
	if v != nil {
		_c.SetDeleteTime(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *NotificationLogCreate) SetTenantID(v uint32) *NotificationLogCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *NotificationLogCreate) SetNillableTenantID(v *uint32) *NotificationLogCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetChannelID sets the "channel_id" field.
func (_c *NotificationLogCreate) SetChannelID(v string) *NotificationLogCreate {
	_c.mutation.SetChannelID(v)
	return _c
}

// SetChannelType sets the "channel_type" field.
func (_c *NotificationLogCreate) SetChannelType(v notificationlog.ChannelType) *NotificationLogCreate {
	_c.mutation.SetChannelType(v)
	return _c
}

// SetTemplateID sets the "template_id" field.
func (_c *NotificationLogCreate) SetTemplateID(v string) *NotificationLogCreate {
	_c.mutation.SetTemplateID(v)
	return _c
}

// SetRecipient sets the "recipient" field.
func (_c *NotificationLogCreate) SetRecipient(v string) *NotificationLogCreate {
	_c.mutation.SetRecipient(v)
	return _c
}

// SetRenderedSubject sets the "rendered_subject" field.
func (_c *NotificationLogCreate) SetRenderedSubject(v string) *NotificationLogCreate {
	_c.mutation.SetRenderedSubject(v)
	return _c
}

// SetNillableRenderedSubject sets the "rendered_subject" field if the given value is not nil.
func (_c *NotificationLogCreate) SetNillableRenderedSubject(v *string) *NotificationLogCreate {
	if v != nil {
		_c.SetRenderedSubject(*v)
	}
	return _c
}

// SetRenderedBody sets the "rendered_body" field.
func (_c *NotificationLogCreate) SetRenderedBody(v string) *NotificationLogCreate {
	_c.mutation.SetRenderedBody(v)
	return _c
}

// SetNillableRenderedBody sets the "rendered_body" field if the given value is not nil.
func (_c *NotificationLogCreate) SetNillableRenderedBody(v *string) *NotificationLogCreate {
	if v != nil {
		_c.SetRenderedBody(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *NotificationLogCreate) SetStatus(v notificationlog.Status) *NotificationLogCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *NotificationLogCreate) SetNillableStatus(v *notificationlog.Status) *NotificationLogCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *NotificationLogCreate) SetErrorMessage(v string) *NotificationLogCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *NotificationLogCreate) SetNillableErrorMessage(v *string) *NotificationLogCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetSentAt sets the "sent_at" field.
func (_c *NotificationLogCreate) SetSentAt(v time.Time) *NotificationLogCreate {
	_c.mutation.SetSentAt(v)
	return _c
}

// SetNillableSentAt sets the "sent_at" field if the given value is not nil.
func (_c *NotificationLogCreate) SetNillableSentAt(v *time.Time) *NotificationLogCreate {
	if v != nil {
		_c.SetSentAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *NotificationLogCreate) SetID(v string) *NotificationLogCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the NotificationLogMutation object of the builder.
func (_c *NotificationLogCreate) Mutation() *NotificationLogMutation {
	return _c.mutation
}

// Save creates the NotificationLog in the database.
func (_c *NotificationLogCreate) Save(ctx context.Context) (*NotificationLog, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NotificationLogCreate) SaveX(ctx context.Context) *NotificationLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotificationLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotificationLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NotificationLogCreate) defaults() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := notificationlog.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.RenderedSubject(); !ok {
		v := notificationlog.DefaultRenderedSubject
		_c.mutation.SetRenderedSubject(v)
	}
	if _, ok := _c.mutation.RenderedBody(); !ok {
		v := notificationlog.DefaultRenderedBody
		_c.mutation.SetRenderedBody(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := notificationlog.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ErrorMessage(); !ok {
		v := notificationlog.DefaultErrorMessage
		_c.mutation.SetErrorMessage(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *NotificationLogCreate) check() error {
	if _, ok := _c.mutation.ChannelID(); !ok {
		return &ValidationError{Name: "channel_id", err: errors.New(`ent: missing required field "NotificationLog.channel_id"`)}
	}
	if v, ok := _c.mutation.ChannelID(); ok {
		if err := notificationlog.ChannelIDValidator(v); err != nil {
			return &ValidationError{Name: "channel_id", err: fmt.Errorf(`ent: validator failed for field "NotificationLog.channel_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ChannelType(); !ok {
		return &ValidationError{Name: "channel_type", err: errors.New(`ent: missing required field "NotificationLog.channel_type"`)}
	}
	if v, ok := _c.mutation.ChannelType(); ok {
		if err := notificationlog.ChannelTypeValidator(v); err != nil {
			return &ValidationError{Name: "channel_type", err: fmt.Errorf(`ent: validator failed for field "NotificationLog.channel_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TemplateID(); !ok {
		return &ValidationError{Name: "template_id", err: errors.New(`ent: missing required field "NotificationLog.template_id"`)}
	}
	if v, ok := _c.mutation.TemplateID(); ok {
		if err := notificationlog.TemplateIDValidator(v); err != nil {
			return &ValidationError{Name: "template_id", err: fmt.Errorf(`ent: validator failed for field "NotificationLog.template_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Recipient(); !ok {
		return &ValidationError{Name: "recipient", err: errors.New(`ent: missing required field "NotificationLog.recipient"`)}
	}
	if v, ok := _c.mutation.Recipient(); ok {
		if err := notificationlog.RecipientValidator(v); err != nil {
			return &ValidationError{Name: "recipient", err: fmt.Errorf(`ent: validator failed for field "NotificationLog.recipient": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RenderedSubject(); !ok {
		return &ValidationError{Name: "rendered_subject", err: errors.New(`ent: missing required field "NotificationLog.rendered_subject"`)}
	}
	if v, ok := _c.mutation.RenderedSubject(); ok {
		if err := notificationlog.RenderedSubjectValidator(v); err != nil {
			return &ValidationError{Name: "rendered_subject", err: fmt.Errorf(`ent: validator failed for field "NotificationLog.rendered_subject": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RenderedBody(); !ok {
		return &ValidationError{Name: "rendered_body", err: errors.New(`ent: missing required field "NotificationLog.rendered_body"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "NotificationLog.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := notificationlog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "NotificationLog.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ErrorMessage(); !ok {
		return &ValidationError{Name: "error_message", err: errors.New(`ent: missing required field "NotificationLog.error_message"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := notificationlog.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "NotificationLog.id": %w`, err)}
		}
	}
	return nil
}

func (_c *NotificationLogCreate) sqlSave(ctx context.Context) (*NotificationLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected NotificationLog.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NotificationLogCreate) createSpec() (*NotificationLog, *sqlgraph.CreateSpec) {
	var (
		_node = &NotificationLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(notificationlog.Table, sqlgraph.NewFieldSpec(notificationlog.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateBy(); ok {
		_spec.SetField(notificationlog.FieldCreateBy, field.TypeUint32, value)
		_node.CreateBy = &value
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(notificationlog.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = &value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(notificationlog.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = &value
	}
	if value, ok := _c.mutation.DeleteTime(); ok {
		_spec.SetField(notificationlog.FieldDeleteTime, field.TypeTime, value)
		_node.DeleteTime = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(notificationlog.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.ChannelID(); ok {
		_spec.SetField(notificationlog.FieldChannelID, field.TypeString, value)
		_node.ChannelID = value
	}
	if value, ok := _c.mutation.ChannelType(); ok {
		_spec.SetField(notificationlog.FieldChannelType, field.TypeEnum, value)
		_node.ChannelType = value
	}
	if value, ok := _c.mutation.TemplateID(); ok {
		_spec.SetField(notificationlog.FieldTemplateID, field.TypeString, value)
		_node.TemplateID = value
	}
	if value, ok := _c.mutation.Recipient(); ok {
		_spec.SetField(notificationlog.FieldRecipient, field.TypeString, value)
		_node.Recipient = value
	}
	if value, ok := _c.mutation.RenderedSubject(); ok {
		_spec.SetField(notificationlog.FieldRenderedSubject, field.TypeString, value)
		_node.RenderedSubject = value
	}
	if value, ok := _c.mutation.RenderedBody(); ok {
		_spec.SetField(notificationlog.FieldRenderedBody, field.TypeString, value)
		_node.RenderedBody = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(notificationlog.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(notificationlog.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = value
	}
	if value, ok := _c.mutation.SentAt(); ok {
		_spec.SetField(notificationlog.FieldSentAt, field.TypeTime, value)
		_node.SentAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NotificationLog.Create().
//		SetCreateBy(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NotificationLogUpsert) {
//			SetCreateBy(v+v).
//		}).
//		Exec(ctx)
func (_c *NotificationLogCreate) OnConflict(opts ...sql.ConflictOption) *NotificationLogUpsertOne {
	_c.conflict = opts
	return &NotificationLogUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NotificationLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *NotificationLogCreate) OnConflictColumns(columns ...string) *NotificationLogUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &NotificationLogUpsertOne{
		create: _c,
	}
}

type (
	// NotificationLogUpsertOne is the builder for "upsert"-ing
	//  one NotificationLog node.
	NotificationLogUpsertOne struct {
		create *NotificationLogCreate
	}

	// NotificationLogUpsert is the "OnConflict" setter.
	NotificationLogUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreateBy sets the "create_by" field.
func (u *NotificationLogUpsert) SetCreateBy(v uint32) *NotificationLogUpsert {
	u.Set(notificationlog.FieldCreateBy, v)
	return u
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *NotificationLogUpsert) UpdateCreateBy() *NotificationLogUpsert {
	u.SetExcluded(notificationlog.FieldCreateBy)
	return u
}

// AddCreateBy adds v to the "create_by" field.
func (u *NotificationLogUpsert) AddCreateBy(v uint32) *NotificationLogUpsert {
	u.Add(notificationlog.FieldCreateBy, v)
	return u
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *NotificationLogUpsert) ClearCreateBy() *NotificationLogUpsert {
	u.SetNull(notificationlog.FieldCreateBy)
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *NotificationLogUpsert) SetUpdateTime(v time.Time) *NotificationLogUpsert {
	u.Set(notificationlog.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *NotificationLogUpsert) UpdateUpdateTime() *NotificationLogUpsert {
	u.SetExcluded(notificationlog.FieldUpdateTime)
	return u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *NotificationLogUpsert) ClearUpdateTime() *NotificationLogUpsert {
	u.SetNull(notificationlog.FieldUpdateTime)
	return u
}

// SetDeleteTime sets the "delete_time" field.
func (u *NotificationLogUpsert) SetDeleteTime(v time.Time) *NotificationLogUpsert {
	u.Set(notificationlog.FieldDeleteTime, v)
	return u
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *NotificationLogUpsert) UpdateDeleteTime() *NotificationLogUpsert {
	u.SetExcluded(notificationlog.FieldDeleteTime)
	return u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *NotificationLogUpsert) ClearDeleteTime() *NotificationLogUpsert {
	u.SetNull(notificationlog.FieldDeleteTime)
	return u
}

// SetChannelID sets the "channel_id" field.
func (u *NotificationLogUpsert) SetChannelID(v string) *NotificationLogUpsert {
	u.Set(notificationlog.FieldChannelID, v)
	return u
}

// UpdateChannelID sets the "channel_id" field to the value that was provided on create.
func (u *NotificationLogUpsert) UpdateChannelID() *NotificationLogUpsert {
	u.SetExcluded(notificationlog.FieldChannelID)
	return u
}

// SetChannelType sets the "channel_type" field.
func (u *NotificationLogUpsert) SetChannelType(v notificationlog.ChannelType) *NotificationLogUpsert {
	u.Set(notificationlog.FieldChannelType, v)
	return u
}

// UpdateChannelType sets the "channel_type" field to the value that was provided on create.
func (u *NotificationLogUpsert) UpdateChannelType() *NotificationLogUpsert {
	u.SetExcluded(notificationlog.FieldChannelType)
	return u
}

// SetTemplateID sets the "template_id" field.
func (u *NotificationLogUpsert) SetTemplateID(v string) *NotificationLogUpsert {
	u.Set(notificationlog.FieldTemplateID, v)
	return u
}

// UpdateTemplateID sets the "template_id" field to the value that was provided on create.
func (u *NotificationLogUpsert) UpdateTemplateID() *NotificationLogUpsert {
	u.SetExcluded(notificationlog.FieldTemplateID)
	return u
}

// SetRecipient sets the "recipient" field.
func (u *NotificationLogUpsert) SetRecipient(v string) *NotificationLogUpsert {
	u.Set(notificationlog.FieldRecipient, v)
	return u
}

// UpdateRecipient sets the "recipient" field to the value that was provided on create.
func (u *NotificationLogUpsert) UpdateRecipient() *NotificationLogUpsert {
	u.SetExcluded(notificationlog.FieldRecipient)
	return u
}

// SetRenderedSubject sets the "rendered_subject" field.
func (u *NotificationLogUpsert) SetRenderedSubject(v string) *NotificationLogUpsert {
	u.Set(notificationlog.FieldRenderedSubject, v)
	return u
}

// UpdateRenderedSubject sets the "rendered_subject" field to the value that was provided on create.
func (u *NotificationLogUpsert) UpdateRenderedSubject() *NotificationLogUpsert {
	u.SetExcluded(notificationlog.FieldRenderedSubject)
	return u
}

// SetRenderedBody sets the "rendered_body" field.
func (u *NotificationLogUpsert) SetRenderedBody(v string) *NotificationLogUpsert {
	u.Set(notificationlog.FieldRenderedBody, v)
	return u
}

// UpdateRenderedBody sets the "rendered_body" field to the value that was provided on create.
func (u *NotificationLogUpsert) UpdateRenderedBody() *NotificationLogUpsert {
	u.SetExcluded(notificationlog.FieldRenderedBody)
	return u
}

// SetStatus sets the "status" field.
func (u *NotificationLogUpsert) SetStatus(v notificationlog.Status) *NotificationLogUpsert {
	u.Set(notificationlog.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *NotificationLogUpsert) UpdateStatus() *NotificationLogUpsert {
	u.SetExcluded(notificationlog.FieldStatus)
	return u
}

// SetErrorMessage sets the "error_message" field.
func (u *NotificationLogUpsert) SetErrorMessage(v string) *NotificationLogUpsert {
	u.Set(notificationlog.FieldErrorMessage, v)
	return u
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *NotificationLogUpsert) UpdateErrorMessage() *NotificationLogUpsert {
	u.SetExcluded(notificationlog.FieldErrorMessage)
	return u
}

// SetSentAt sets the "sent_at" field.
func (u *NotificationLogUpsert) SetSentAt(v time.Time) *NotificationLogUpsert {
	u.Set(notificationlog.FieldSentAt, v)
	return u
}

// UpdateSentAt sets the "sent_at" field to the value that was provided on create.
func (u *NotificationLogUpsert) UpdateSentAt() *NotificationLogUpsert {
	u.SetExcluded(notificationlog.FieldSentAt)
	return u
}

// ClearSentAt clears the value of the "sent_at" field.
func (u *NotificationLogUpsert) ClearSentAt() *NotificationLogUpsert {
	u.SetNull(notificationlog.FieldSentAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.NotificationLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(notificationlog.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *NotificationLogUpsertOne) UpdateNewValues() *NotificationLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(notificationlog.FieldID)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(notificationlog.FieldCreateTime)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(notificationlog.FieldTenantID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NotificationLog.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *NotificationLogUpsertOne) Ignore() *NotificationLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NotificationLogUpsertOne) DoNothing() *NotificationLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NotificationLogCreate.OnConflict
// documentation for more info.
func (u *NotificationLogUpsertOne) Update(set func(*NotificationLogUpsert)) *NotificationLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NotificationLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreateBy sets the "create_by" field.
func (u *NotificationLogUpsertOne) SetCreateBy(v uint32) *NotificationLogUpsertOne {
	return u.Update(func(s *NotificationLogUpsert) {
		s.SetCreateBy(v)
	})
}

// AddCreateBy adds v to the "create_by" field.
func (u *NotificationLogUpsertOne) AddCreateBy(v uint32) *NotificationLogUpsertOne {
	return u.Update(func(s *NotificationLogUpsert) {
		s.AddCreateBy(v)
	})
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *NotificationLogUpsertOne) UpdateCreateBy() *NotificationLogUpsertOne {
	return u.Update(func(s *NotificationLogUpsert) {
		s.UpdateCreateBy()
	})
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *NotificationLogUpsertOne) ClearCreateBy() *NotificationLogUpsertOne {
	return u.Update(func(s *NotificationLogUpsert) {
		s.ClearCreateBy()
	})
}

// SetUpdateTime sets the "update_time" field.
func (u *NotificationLogUpsertOne) SetUpdateTime(v time.Time) *NotificationLogUpsertOne {
	return u.Update(func(s *NotificationLogUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *NotificationLogUpsertOne) UpdateUpdateTime() *NotificationLogUpsertOne {
	return u.Update(func(s *NotificationLogUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *NotificationLogUpsertOne) ClearUpdateTime() *NotificationLogUpsertOne {
	return u.Update(func(s *NotificationLogUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *NotificationLogUpsertOne) SetDeleteTime(v time.Time) *NotificationLogUpsertOne {
	return u.Update(func(s *NotificationLogUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *NotificationLogUpsertOne) UpdateDeleteTime() *NotificationLogUpsertOne {
	return u.Update(func(s *NotificationLogUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *NotificationLogUpsertOne) ClearDeleteTime() *NotificationLogUpsertOne {
	return u.Update(func(s *NotificationLogUpsert) {
		s.ClearDeleteTime()
	})
}

// SetChannelID sets the "channel_id" field.
func (u *NotificationLogUpsertOne) SetChannelID(v string) *NotificationLogUpsertOne {
	return u.Update(func(s *NotificationLogUpsert) {
		s.SetChannelID(v)
	})
}

// UpdateChannelID sets the "channel_id" field to the value that was provided on create.
func (u *NotificationLogUpsertOne) UpdateChannelID() *NotificationLogUpsertOne {
	return u.Update(func(s *NotificationLogUpsert) {
		s.UpdateChannelID()
	})
}

// SetChannelType sets the "channel_type" field.
func (u *NotificationLogUpsertOne) SetChannelType(v notificationlog.ChannelType) *NotificationLogUpsertOne {
	return u.Update(func(s *NotificationLogUpsert) {
		s.SetChannelType(v)
	})
}

// UpdateChannelType sets the "channel_type" field to the value that was provided on create.
func (u *NotificationLogUpsertOne) UpdateChannelType() *NotificationLogUpsertOne {
	return u.Update(func(s *NotificationLogUpsert) {
		s.UpdateChannelType()
	})
}

// SetTemplateID sets the "template_id" field.
func (u *NotificationLogUpsertOne) SetTemplateID(v string) *NotificationLogUpsertOne {
	return u.Update(func(s *NotificationLogUpsert) {
		s.SetTemplateID(v)
	})
}

// UpdateTemplateID sets the "template_id" field to the value that was provided on create.
func (u *NotificationLogUpsertOne) UpdateTemplateID() *NotificationLogUpsertOne {
	return u.Update(func(s *NotificationLogUpsert) {
		s.UpdateTemplateID()
	})
}

// SetRecipient sets the "recipient" field.
func (u *NotificationLogUpsertOne) SetRecipient(v string) *NotificationLogUpsertOne {
	return u.Update(func(s *NotificationLogUpsert) {
		s.SetRecipient(v)
	})
}

// UpdateRecipient sets the "recipient" field to the value that was provided on create.
func (u *NotificationLogUpsertOne) UpdateRecipient() *NotificationLogUpsertOne {
	return u.Update(func(s *NotificationLogUpsert) {
		s.UpdateRecipient()
	})
}

// SetRenderedSubject sets the "rendered_subject" field.
func (u *NotificationLogUpsertOne) SetRenderedSubject(v string) *NotificationLogUpsertOne {
	return u.Update(func(s *NotificationLogUpsert) {
		s.SetRenderedSubject(v)
	})
}

// UpdateRenderedSubject sets the "rendered_subject" field to the value that was provided on create.
func (u *NotificationLogUpsertOne) UpdateRenderedSubject() *NotificationLogUpsertOne {
	return u.Update(func(s *NotificationLogUpsert) {
		s.UpdateRenderedSubject()
	})
}

// SetRenderedBody sets the "rendered_body" field.
func (u *NotificationLogUpsertOne) SetRenderedBody(v string) *NotificationLogUpsertOne {
	return u.Update(func(s *NotificationLogUpsert) {
		s.SetRenderedBody(v)
	})
}

// UpdateRenderedBody sets the "rendered_body" field to the value that was provided on create.
func (u *NotificationLogUpsertOne) UpdateRenderedBody() *NotificationLogUpsertOne {
	return u.Update(func(s *NotificationLogUpsert) {
		s.UpdateRenderedBody()
	})
}

// SetStatus sets the "status" field.
func (u *NotificationLogUpsertOne) SetStatus(v notificationlog.Status) *NotificationLogUpsertOne {
	return u.Update(func(s *NotificationLogUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *NotificationLogUpsertOne) UpdateStatus() *NotificationLogUpsertOne {
	return u.Update(func(s *NotificationLogUpsert) {
		s.UpdateStatus()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *NotificationLogUpsertOne) SetErrorMessage(v string) *NotificationLogUpsertOne {
	return u.Update(func(s *NotificationLogUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *NotificationLogUpsertOne) UpdateErrorMessage() *NotificationLogUpsertOne {
	return u.Update(func(s *NotificationLogUpsert) {
		s.UpdateErrorMessage()
	})
}

// SetSentAt sets the "sent_at" field.
func (u *NotificationLogUpsertOne) SetSentAt(v time.Time) *NotificationLogUpsertOne {
	return u.Update(func(s *NotificationLogUpsert) {
		s.SetSentAt(v)
	})
}

// UpdateSentAt sets the "sent_at" field to the value that was provided on create.
func (u *NotificationLogUpsertOne) UpdateSentAt() *NotificationLogUpsertOne {
	return u.Update(func(s *NotificationLogUpsert) {
		s.UpdateSentAt()
	})
}

// ClearSentAt clears the value of the "sent_at" field.
func (u *NotificationLogUpsertOne) ClearSentAt() *NotificationLogUpsertOne {
	return u.Update(func(s *NotificationLogUpsert) {
		s.ClearSentAt()
	})
}

// Exec executes the query.
func (u *NotificationLogUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NotificationLogCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NotificationLogUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *NotificationLogUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: NotificationLogUpsertOne.ID is not supported by MySQL driver. Use NotificationLogUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *NotificationLogUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// NotificationLogCreateBulk is the builder for creating many NotificationLog entities in bulk.
type NotificationLogCreateBulk struct {
	config
	err      error
	builders []*NotificationLogCreate
	conflict []sql.ConflictOption
}

// Save creates the NotificationLog entities in the database.
func (_c *NotificationLogCreateBulk) Save(ctx context.Context) ([]*NotificationLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*NotificationLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NotificationLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NotificationLogCreateBulk) SaveX(ctx context.Context) []*NotificationLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotificationLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotificationLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NotificationLog.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NotificationLogUpsert) {
//			SetCreateBy(v+v).
//		}).
//		Exec(ctx)
func (_c *NotificationLogCreateBulk) OnConflict(opts ...sql.ConflictOption) *NotificationLogUpsertBulk {
	_c.conflict = opts
	return &NotificationLogUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NotificationLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *NotificationLogCreateBulk) OnConflictColumns(columns ...string) *NotificationLogUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &NotificationLogUpsertBulk{
		create: _c,
	}
}

// NotificationLogUpsertBulk is the builder for "upsert"-ing
// a bulk of NotificationLog nodes.
type NotificationLogUpsertBulk struct {
	create *NotificationLogCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.NotificationLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(notificationlog.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *NotificationLogUpsertBulk) UpdateNewValues() *NotificationLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(notificationlog.FieldID)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(notificationlog.FieldCreateTime)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(notificationlog.FieldTenantID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NotificationLog.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *NotificationLogUpsertBulk) Ignore() *NotificationLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NotificationLogUpsertBulk) DoNothing() *NotificationLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NotificationLogCreateBulk.OnConflict
// documentation for more info.
func (u *NotificationLogUpsertBulk) Update(set func(*NotificationLogUpsert)) *NotificationLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NotificationLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreateBy sets the "create_by" field.
func (u *NotificationLogUpsertBulk) SetCreateBy(v uint32) *NotificationLogUpsertBulk {
	return u.Update(func(s *NotificationLogUpsert) {
		s.SetCreateBy(v)
	})
}

// AddCreateBy adds v to the "create_by" field.
func (u *NotificationLogUpsertBulk) AddCreateBy(v uint32) *NotificationLogUpsertBulk {
	return u.Update(func(s *NotificationLogUpsert) {
		s.AddCreateBy(v)
	})
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *NotificationLogUpsertBulk) UpdateCreateBy() *NotificationLogUpsertBulk {
	return u.Update(func(s *NotificationLogUpsert) {
		s.UpdateCreateBy()
	})
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *NotificationLogUpsertBulk) ClearCreateBy() *NotificationLogUpsertBulk {
	return u.Update(func(s *NotificationLogUpsert) {
		s.ClearCreateBy()
	})
}

// SetUpdateTime sets the "update_time" field.
func (u *NotificationLogUpsertBulk) SetUpdateTime(v time.Time) *NotificationLogUpsertBulk {
	return u.Update(func(s *NotificationLogUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *NotificationLogUpsertBulk) UpdateUpdateTime() *NotificationLogUpsertBulk {
	return u.Update(func(s *NotificationLogUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *NotificationLogUpsertBulk) ClearUpdateTime() *NotificationLogUpsertBulk {
	return u.Update(func(s *NotificationLogUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *NotificationLogUpsertBulk) SetDeleteTime(v time.Time) *NotificationLogUpsertBulk {
	return u.Update(func(s *NotificationLogUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *NotificationLogUpsertBulk) UpdateDeleteTime() *NotificationLogUpsertBulk {
	return u.Update(func(s *NotificationLogUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *NotificationLogUpsertBulk) ClearDeleteTime() *NotificationLogUpsertBulk {
	return u.Update(func(s *NotificationLogUpsert) {
		s.ClearDeleteTime()
	})
}

// SetChannelID sets the "channel_id" field.
func (u *NotificationLogUpsertBulk) SetChannelID(v string) *NotificationLogUpsertBulk {
	return u.Update(func(s *NotificationLogUpsert) {
		s.SetChannelID(v)
	})
}

// UpdateChannelID sets the "channel_id" field to the value that was provided on create.
func (u *NotificationLogUpsertBulk) UpdateChannelID() *NotificationLogUpsertBulk {
	return u.Update(func(s *NotificationLogUpsert) {
		s.UpdateChannelID()
	})
}

// SetChannelType sets the "channel_type" field.
func (u *NotificationLogUpsertBulk) SetChannelType(v notificationlog.ChannelType) *NotificationLogUpsertBulk {
	return u.Update(func(s *NotificationLogUpsert) {
		s.SetChannelType(v)
	})
}

// UpdateChannelType sets the "channel_type" field to the value that was provided on create.
func (u *NotificationLogUpsertBulk) UpdateChannelType() *NotificationLogUpsertBulk {
	return u.Update(func(s *NotificationLogUpsert) {
		s.UpdateChannelType()
	})
}

// SetTemplateID sets the "template_id" field.
func (u *NotificationLogUpsertBulk) SetTemplateID(v string) *NotificationLogUpsertBulk {
	return u.Update(func(s *NotificationLogUpsert) {
		s.SetTemplateID(v)
	})
}

// UpdateTemplateID sets the "template_id" field to the value that was provided on create.
func (u *NotificationLogUpsertBulk) UpdateTemplateID() *NotificationLogUpsertBulk {
	return u.Update(func(s *NotificationLogUpsert) {
		s.UpdateTemplateID()
	})
}

// SetRecipient sets the "recipient" field.
func (u *NotificationLogUpsertBulk) SetRecipient(v string) *NotificationLogUpsertBulk {
	return u.Update(func(s *NotificationLogUpsert) {
		s.SetRecipient(v)
	})
}

// UpdateRecipient sets the "recipient" field to the value that was provided on create.
func (u *NotificationLogUpsertBulk) UpdateRecipient() *NotificationLogUpsertBulk {
	return u.Update(func(s *NotificationLogUpsert) {
		s.UpdateRecipient()
	})
}

// SetRenderedSubject sets the "rendered_subject" field.
func (u *NotificationLogUpsertBulk) SetRenderedSubject(v string) *NotificationLogUpsertBulk {
	return u.Update(func(s *NotificationLogUpsert) {
		s.SetRenderedSubject(v)
	})
}

// UpdateRenderedSubject sets the "rendered_subject" field to the value that was provided on create.
func (u *NotificationLogUpsertBulk) UpdateRenderedSubject() *NotificationLogUpsertBulk {
	return u.Update(func(s *NotificationLogUpsert) {
		s.UpdateRenderedSubject()
	})
}

// SetRenderedBody sets the "rendered_body" field.
func (u *NotificationLogUpsertBulk) SetRenderedBody(v string) *NotificationLogUpsertBulk {
	return u.Update(func(s *NotificationLogUpsert) {
		s.SetRenderedBody(v)
	})
}

// UpdateRenderedBody sets the "rendered_body" field to the value that was provided on create.
func (u *NotificationLogUpsertBulk) UpdateRenderedBody() *NotificationLogUpsertBulk {
	return u.Update(func(s *NotificationLogUpsert) {
		s.UpdateRenderedBody()
	})
}

// SetStatus sets the "status" field.
func (u *NotificationLogUpsertBulk) SetStatus(v notificationlog.Status) *NotificationLogUpsertBulk {
	return u.Update(func(s *NotificationLogUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *NotificationLogUpsertBulk) UpdateStatus() *NotificationLogUpsertBulk {
	return u.Update(func(s *NotificationLogUpsert) {
		s.UpdateStatus()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *NotificationLogUpsertBulk) SetErrorMessage(v string) *NotificationLogUpsertBulk {
	return u.Update(func(s *NotificationLogUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *NotificationLogUpsertBulk) UpdateErrorMessage() *NotificationLogUpsertBulk {
	return u.Update(func(s *NotificationLogUpsert) {
		s.UpdateErrorMessage()
	})
}

// SetSentAt sets the "sent_at" field.
func (u *NotificationLogUpsertBulk) SetSentAt(v time.Time) *NotificationLogUpsertBulk {
	return u.Update(func(s *NotificationLogUpsert) {
		s.SetSentAt(v)
	})
}

// UpdateSentAt sets the "sent_at" field to the value that was provided on create.
func (u *NotificationLogUpsertBulk) UpdateSentAt() *NotificationLogUpsertBulk {
	return u.Update(func(s *NotificationLogUpsert) {
		s.UpdateSentAt()
	})
}

// ClearSentAt clears the value of the "sent_at" field.
func (u *NotificationLogUpsertBulk) ClearSentAt() *NotificationLogUpsertBulk {
	return u.Update(func(s *NotificationLogUpsert) {
		s.ClearSentAt()
	})
}

// Exec executes the query.
func (u *NotificationLogUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the NotificationLogCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NotificationLogCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NotificationLogUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
