// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-notification/internal/data/ent/predicate"
	"github.com/go-tangra/go-tangra-notification/internal/data/ent/template"
)

// TemplateUpdate is the builder for updating Template entities.
type TemplateUpdate struct {
	config
	hooks     []Hook
	mutation  *TemplateMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the TemplateUpdate builder.
func (_u *TemplateUpdate) Where(ps ...predicate.Template) *TemplateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreateBy sets the "create_by" field.
func (_u *TemplateUpdate) SetCreateBy(v uint32) *TemplateUpdate {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *TemplateUpdate) SetNillableCreateBy(v *uint32) *TemplateUpdate {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *TemplateUpdate) AddCreateBy(v int32) *TemplateUpdate {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *TemplateUpdate) ClearCreateBy() *TemplateUpdate {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateBy sets the "update_by" field.
func (_u *TemplateUpdate) SetUpdateBy(v uint32) *TemplateUpdate {
	_u.mutation.ResetUpdateBy()
	_u.mutation.SetUpdateBy(v)
	return _u
}

// SetNillableUpdateBy sets the "update_by" field if the given value is not nil.
func (_u *TemplateUpdate) SetNillableUpdateBy(v *uint32) *TemplateUpdate {
	if v != nil {
		_u.SetUpdateBy(*v)
	}
	return _u
}

// AddUpdateBy adds value to the "update_by" field.
func (_u *TemplateUpdate) AddUpdateBy(v int32) *TemplateUpdate {
	_u.mutation.AddUpdateBy(v)
	return _u
}

// ClearUpdateBy clears the value of the "update_by" field.
func (_u *TemplateUpdate) ClearUpdateBy() *TemplateUpdate {
	_u.mutation.ClearUpdateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *TemplateUpdate) SetUpdateTime(v time.Time) *TemplateUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *TemplateUpdate) SetNillableUpdateTime(v *time.Time) *TemplateUpdate {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *TemplateUpdate) ClearUpdateTime() *TemplateUpdate {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *TemplateUpdate) SetDeleteTime(v time.Time) *TemplateUpdate {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *TemplateUpdate) SetNillableDeleteTime(v *time.Time) *TemplateUpdate {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *TemplateUpdate) ClearDeleteTime() *TemplateUpdate {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetName sets the "name" field.
func (_u *TemplateUpdate) SetName(v string) *TemplateUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TemplateUpdate) SetNillableName(v *string) *TemplateUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *TemplateUpdate) SetChannelID(v string) *TemplateUpdate {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *TemplateUpdate) SetNillableChannelID(v *string) *TemplateUpdate {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// SetSubject sets the "subject" field.
func (_u *TemplateUpdate) SetSubject(v string) *TemplateUpdate {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *TemplateUpdate) SetNillableSubject(v *string) *TemplateUpdate {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetBody sets the "body" field.
func (_u *TemplateUpdate) SetBody(v string) *TemplateUpdate {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *TemplateUpdate) SetNillableBody(v *string) *TemplateUpdate {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetVariables sets the "variables" field.
func (_u *TemplateUpdate) SetVariables(v string) *TemplateUpdate {
	_u.mutation.SetVariables(v)
	return _u
}

// SetNillableVariables sets the "variables" field if the given value is not nil.
func (_u *TemplateUpdate) SetNillableVariables(v *string) *TemplateUpdate {
	if v != nil {
		_u.SetVariables(*v)
	}
	return _u
}

// SetIsDefault sets the "is_default" field.
func (_u *TemplateUpdate) SetIsDefault(v bool) *TemplateUpdate {
	_u.mutation.SetIsDefault(v)
	return _u
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_u *TemplateUpdate) SetNillableIsDefault(v *bool) *TemplateUpdate {
	if v != nil {
		_u.SetIsDefault(*v)
	}
	return _u
}

// Mutation returns the TemplateMutation object of the builder.
func (_u *TemplateUpdate) Mutation() *TemplateMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TemplateUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TemplateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TemplateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TemplateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TemplateUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := template.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Template.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChannelID(); ok {
		if err := template.ChannelIDValidator(v); err != nil {
			return &ValidationError{Name: "channel_id", err: fmt.Errorf(`ent: validator failed for field "Template.channel_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Subject(); ok {
		if err := template.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "Template.subject": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Body(); ok {
		if err := template.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`ent: validator failed for field "Template.body": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Variables(); ok {
		if err := template.VariablesValidator(v); err != nil {
			return &ValidationError{Name: "variables", err: fmt.Errorf(`ent: validator failed for field "Template.variables": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *TemplateUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TemplateUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *TemplateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(template.Table, template.Columns, sqlgraph.NewFieldSpec(template.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(template.FieldCreateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(template.FieldCreateBy, field.TypeUint32, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(template.FieldCreateBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdateBy(); ok {
		_spec.SetField(template.FieldUpdateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdateBy(); ok {
		_spec.AddField(template.FieldUpdateBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdateByCleared() {
		_spec.ClearField(template.FieldUpdateBy, field.TypeUint32)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(template.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(template.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(template.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(template.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(template.FieldDeleteTime, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(template.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(template.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChannelID(); ok {
		_spec.SetField(template.FieldChannelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(template.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(template.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.Variables(); ok {
		_spec.SetField(template.FieldVariables, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsDefault(); ok {
		_spec.SetField(template.FieldIsDefault, field.TypeBool, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{template.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TemplateUpdateOne is the builder for updating a single Template entity.
type TemplateUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *TemplateMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetCreateBy sets the "create_by" field.
func (_u *TemplateUpdateOne) SetCreateBy(v uint32) *TemplateUpdateOne {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *TemplateUpdateOne) SetNillableCreateBy(v *uint32) *TemplateUpdateOne {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *TemplateUpdateOne) AddCreateBy(v int32) *TemplateUpdateOne {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *TemplateUpdateOne) ClearCreateBy() *TemplateUpdateOne {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateBy sets the "update_by" field.
func (_u *TemplateUpdateOne) SetUpdateBy(v uint32) *TemplateUpdateOne {
	_u.mutation.ResetUpdateBy()
	_u.mutation.SetUpdateBy(v)
	return _u
}

// SetNillableUpdateBy sets the "update_by" field if the given value is not nil.
func (_u *TemplateUpdateOne) SetNillableUpdateBy(v *uint32) *TemplateUpdateOne {
	if v != nil {
		_u.SetUpdateBy(*v)
	}
	return _u
}

// AddUpdateBy adds value to the "update_by" field.
func (_u *TemplateUpdateOne) AddUpdateBy(v int32) *TemplateUpdateOne {
	_u.mutation.AddUpdateBy(v)
	return _u
}

// ClearUpdateBy clears the value of the "update_by" field.
func (_u *TemplateUpdateOne) ClearUpdateBy() *TemplateUpdateOne {
	_u.mutation.ClearUpdateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *TemplateUpdateOne) SetUpdateTime(v time.Time) *TemplateUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *TemplateUpdateOne) SetNillableUpdateTime(v *time.Time) *TemplateUpdateOne {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *TemplateUpdateOne) ClearUpdateTime() *TemplateUpdateOne {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *TemplateUpdateOne) SetDeleteTime(v time.Time) *TemplateUpdateOne {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *TemplateUpdateOne) SetNillableDeleteTime(v *time.Time) *TemplateUpdateOne {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *TemplateUpdateOne) ClearDeleteTime() *TemplateUpdateOne {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetName sets the "name" field.
func (_u *TemplateUpdateOne) SetName(v string) *TemplateUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TemplateUpdateOne) SetNillableName(v *string) *TemplateUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *TemplateUpdateOne) SetChannelID(v string) *TemplateUpdateOne {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *TemplateUpdateOne) SetNillableChannelID(v *string) *TemplateUpdateOne {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// SetSubject sets the "subject" field.
func (_u *TemplateUpdateOne) SetSubject(v string) *TemplateUpdateOne {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *TemplateUpdateOne) SetNillableSubject(v *string) *TemplateUpdateOne {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetBody sets the "body" field.
func (_u *TemplateUpdateOne) SetBody(v string) *TemplateUpdateOne {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *TemplateUpdateOne) SetNillableBody(v *string) *TemplateUpdateOne {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetVariables sets the "variables" field.
func (_u *TemplateUpdateOne) SetVariables(v string) *TemplateUpdateOne {
	_u.mutation.SetVariables(v)
	return _u
}

// SetNillableVariables sets the "variables" field if the given value is not nil.
func (_u *TemplateUpdateOne) SetNillableVariables(v *string) *TemplateUpdateOne {
	if v != nil {
		_u.SetVariables(*v)
	}
	return _u
}

// SetIsDefault sets the "is_default" field.
func (_u *TemplateUpdateOne) SetIsDefault(v bool) *TemplateUpdateOne {
	_u.mutation.SetIsDefault(v)
	return _u
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_u *TemplateUpdateOne) SetNillableIsDefault(v *bool) *TemplateUpdateOne {
	if v != nil {
		_u.SetIsDefault(*v)
	}
	return _u
}

// Mutation returns the TemplateMutation object of the builder.
func (_u *TemplateUpdateOne) Mutation() *TemplateMutation {
	return _u.mutation
}

// Where appends a list predicates to the TemplateUpdate builder.
func (_u *TemplateUpdateOne) Where(ps ...predicate.Template) *TemplateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TemplateUpdateOne) Select(field string, fields ...string) *TemplateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Template entity.
func (_u *TemplateUpdateOne) Save(ctx context.Context) (*Template, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TemplateUpdateOne) SaveX(ctx context.Context) *Template {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TemplateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TemplateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TemplateUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := template.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Template.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChannelID(); ok {
		if err := template.ChannelIDValidator(v); err != nil {
			return &ValidationError{Name: "channel_id", err: fmt.Errorf(`ent: validator failed for field "Template.channel_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Subject(); ok {
		if err := template.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "Template.subject": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Body(); ok {
		if err := template.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`ent: validator failed for field "Template.body": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Variables(); ok {
		if err := template.VariablesValidator(v); err != nil {
			return &ValidationError{Name: "variables", err: fmt.Errorf(`ent: validator failed for field "Template.variables": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *TemplateUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TemplateUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *TemplateUpdateOne) sqlSave(ctx context.Context) (_node *Template, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(template.Table, template.Columns, sqlgraph.NewFieldSpec(template.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Template.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, template.FieldID)
		for _, f := range fields {
			if !template.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != template.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(template.FieldCreateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(template.FieldCreateBy, field.TypeUint32, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(template.FieldCreateBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdateBy(); ok {
		_spec.SetField(template.FieldUpdateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdateBy(); ok {
		_spec.AddField(template.FieldUpdateBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdateByCleared() {
		_spec.ClearField(template.FieldUpdateBy, field.TypeUint32)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(template.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(template.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(template.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(template.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(template.FieldDeleteTime, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(template.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(template.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChannelID(); ok {
		_spec.SetField(template.FieldChannelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(template.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(template.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.Variables(); ok {
		_spec.SetField(template.FieldVariables, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsDefault(); ok {
		_spec.SetField(template.FieldIsDefault, field.TypeBool, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Template{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{template.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
