// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-notification/internal/data/ent/predicate"
	"github.com/go-tangra/go-tangra-notification/internal/data/ent/templatepermission"
)

// TemplatePermissionUpdate is the builder for updating TemplatePermission entities.
type TemplatePermissionUpdate struct {
	config
	hooks     []Hook
	mutation  *TemplatePermissionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the TemplatePermissionUpdate builder.
func (_u *TemplatePermissionUpdate) Where(ps ...predicate.TemplatePermission) *TemplatePermissionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *TemplatePermissionUpdate) SetUpdateTime(v time.Time) *TemplatePermissionUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *TemplatePermissionUpdate) SetNillableUpdateTime(v *time.Time) *TemplatePermissionUpdate {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *TemplatePermissionUpdate) ClearUpdateTime() *TemplatePermissionUpdate {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *TemplatePermissionUpdate) SetDeleteTime(v time.Time) *TemplatePermissionUpdate {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *TemplatePermissionUpdate) SetNillableDeleteTime(v *time.Time) *TemplatePermissionUpdate {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *TemplatePermissionUpdate) ClearDeleteTime() *TemplatePermissionUpdate {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetResourceType sets the "resource_type" field.
func (_u *TemplatePermissionUpdate) SetResourceType(v templatepermission.ResourceType) *TemplatePermissionUpdate {
	_u.mutation.SetResourceType(v)
	return _u
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (_u *TemplatePermissionUpdate) SetNillableResourceType(v *templatepermission.ResourceType) *TemplatePermissionUpdate {
	if v != nil {
		_u.SetResourceType(*v)
	}
	return _u
}

// SetResourceID sets the "resource_id" field.
func (_u *TemplatePermissionUpdate) SetResourceID(v string) *TemplatePermissionUpdate {
	_u.mutation.SetResourceID(v)
	return _u
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_u *TemplatePermissionUpdate) SetNillableResourceID(v *string) *TemplatePermissionUpdate {
	if v != nil {
		_u.SetResourceID(*v)
	}
	return _u
}

// SetRelation sets the "relation" field.
func (_u *TemplatePermissionUpdate) SetRelation(v templatepermission.Relation) *TemplatePermissionUpdate {
	_u.mutation.SetRelation(v)
	return _u
}

// SetNillableRelation sets the "relation" field if the given value is not nil.
func (_u *TemplatePermissionUpdate) SetNillableRelation(v *templatepermission.Relation) *TemplatePermissionUpdate {
	if v != nil {
		_u.SetRelation(*v)
	}
	return _u
}

// SetSubjectType sets the "subject_type" field.
func (_u *TemplatePermissionUpdate) SetSubjectType(v templatepermission.SubjectType) *TemplatePermissionUpdate {
	_u.mutation.SetSubjectType(v)
	return _u
}

// SetNillableSubjectType sets the "subject_type" field if the given value is not nil.
func (_u *TemplatePermissionUpdate) SetNillableSubjectType(v *templatepermission.SubjectType) *TemplatePermissionUpdate {
	if v != nil {
		_u.SetSubjectType(*v)
	}
	return _u
}

// SetSubjectID sets the "subject_id" field.
func (_u *TemplatePermissionUpdate) SetSubjectID(v string) *TemplatePermissionUpdate {
	_u.mutation.SetSubjectID(v)
	return _u
}

// SetNillableSubjectID sets the "subject_id" field if the given value is not nil.
func (_u *TemplatePermissionUpdate) SetNillableSubjectID(v *string) *TemplatePermissionUpdate {
	if v != nil {
		_u.SetSubjectID(*v)
	}
	return _u
}

// SetGrantedBy sets the "granted_by" field.
func (_u *TemplatePermissionUpdate) SetGrantedBy(v uint32) *TemplatePermissionUpdate {
	_u.mutation.ResetGrantedBy()
	_u.mutation.SetGrantedBy(v)
	return _u
}

// SetNillableGrantedBy sets the "granted_by" field if the given value is not nil.
func (_u *TemplatePermissionUpdate) SetNillableGrantedBy(v *uint32) *TemplatePermissionUpdate {
	if v != nil {
		_u.SetGrantedBy(*v)
	}
	return _u
}

// AddGrantedBy adds value to the "granted_by" field.
func (_u *TemplatePermissionUpdate) AddGrantedBy(v int32) *TemplatePermissionUpdate {
	_u.mutation.AddGrantedBy(v)
	return _u
}

// ClearGrantedBy clears the value of the "granted_by" field.
func (_u *TemplatePermissionUpdate) ClearGrantedBy() *TemplatePermissionUpdate {
	_u.mutation.ClearGrantedBy()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *TemplatePermissionUpdate) SetExpiresAt(v time.Time) *TemplatePermissionUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *TemplatePermissionUpdate) SetNillableExpiresAt(v *time.Time) *TemplatePermissionUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *TemplatePermissionUpdate) ClearExpiresAt() *TemplatePermissionUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// Mutation returns the TemplatePermissionMutation object of the builder.
func (_u *TemplatePermissionUpdate) Mutation() *TemplatePermissionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TemplatePermissionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TemplatePermissionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TemplatePermissionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TemplatePermissionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TemplatePermissionUpdate) check() error {
	if v, ok := _u.mutation.ResourceType(); ok {
		if err := templatepermission.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "TemplatePermission.resource_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResourceID(); ok {
		if err := templatepermission.ResourceIDValidator(v); err != nil {
			return &ValidationError{Name: "resource_id", err: fmt.Errorf(`ent: validator failed for field "TemplatePermission.resource_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Relation(); ok {
		if err := templatepermission.RelationValidator(v); err != nil {
			return &ValidationError{Name: "relation", err: fmt.Errorf(`ent: validator failed for field "TemplatePermission.relation": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SubjectType(); ok {
		if err := templatepermission.SubjectTypeValidator(v); err != nil {
			return &ValidationError{Name: "subject_type", err: fmt.Errorf(`ent: validator failed for field "TemplatePermission.subject_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SubjectID(); ok {
		if err := templatepermission.SubjectIDValidator(v); err != nil {
			return &ValidationError{Name: "subject_id", err: fmt.Errorf(`ent: validator failed for field "TemplatePermission.subject_id": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *TemplatePermissionUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TemplatePermissionUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *TemplatePermissionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(templatepermission.Table, templatepermission.Columns, sqlgraph.NewFieldSpec(templatepermission.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(templatepermission.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(templatepermission.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(templatepermission.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(templatepermission.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(templatepermission.FieldDeleteTime, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(templatepermission.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.ResourceType(); ok {
		_spec.SetField(templatepermission.FieldResourceType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ResourceID(); ok {
		_spec.SetField(templatepermission.FieldResourceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Relation(); ok {
		_spec.SetField(templatepermission.FieldRelation, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SubjectType(); ok {
		_spec.SetField(templatepermission.FieldSubjectType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SubjectID(); ok {
		_spec.SetField(templatepermission.FieldSubjectID, field.TypeString, value)
	}
	if value, ok := _u.mutation.GrantedBy(); ok {
		_spec.SetField(templatepermission.FieldGrantedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedGrantedBy(); ok {
		_spec.AddField(templatepermission.FieldGrantedBy, field.TypeUint32, value)
	}
	if _u.mutation.GrantedByCleared() {
		_spec.ClearField(templatepermission.FieldGrantedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(templatepermission.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(templatepermission.FieldExpiresAt, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{templatepermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TemplatePermissionUpdateOne is the builder for updating a single TemplatePermission entity.
type TemplatePermissionUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *TemplatePermissionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdateTime sets the "update_time" field.
func (_u *TemplatePermissionUpdateOne) SetUpdateTime(v time.Time) *TemplatePermissionUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *TemplatePermissionUpdateOne) SetNillableUpdateTime(v *time.Time) *TemplatePermissionUpdateOne {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *TemplatePermissionUpdateOne) ClearUpdateTime() *TemplatePermissionUpdateOne {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *TemplatePermissionUpdateOne) SetDeleteTime(v time.Time) *TemplatePermissionUpdateOne {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *TemplatePermissionUpdateOne) SetNillableDeleteTime(v *time.Time) *TemplatePermissionUpdateOne {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *TemplatePermissionUpdateOne) ClearDeleteTime() *TemplatePermissionUpdateOne {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetResourceType sets the "resource_type" field.
func (_u *TemplatePermissionUpdateOne) SetResourceType(v templatepermission.ResourceType) *TemplatePermissionUpdateOne {
	_u.mutation.SetResourceType(v)
	return _u
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (_u *TemplatePermissionUpdateOne) SetNillableResourceType(v *templatepermission.ResourceType) *TemplatePermissionUpdateOne {
	if v != nil {
		_u.SetResourceType(*v)
	}
	return _u
}

// SetResourceID sets the "resource_id" field.
func (_u *TemplatePermissionUpdateOne) SetResourceID(v string) *TemplatePermissionUpdateOne {
	_u.mutation.SetResourceID(v)
	return _u
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_u *TemplatePermissionUpdateOne) SetNillableResourceID(v *string) *TemplatePermissionUpdateOne {
	if v != nil {
		_u.SetResourceID(*v)
	}
	return _u
}

// SetRelation sets the "relation" field.
func (_u *TemplatePermissionUpdateOne) SetRelation(v templatepermission.Relation) *TemplatePermissionUpdateOne {
	_u.mutation.SetRelation(v)
	return _u
}

// SetNillableRelation sets the "relation" field if the given value is not nil.
func (_u *TemplatePermissionUpdateOne) SetNillableRelation(v *templatepermission.Relation) *TemplatePermissionUpdateOne {
	if v != nil {
		_u.SetRelation(*v)
	}
	return _u
}

// SetSubjectType sets the "subject_type" field.
func (_u *TemplatePermissionUpdateOne) SetSubjectType(v templatepermission.SubjectType) *TemplatePermissionUpdateOne {
	_u.mutation.SetSubjectType(v)
	return _u
}

// SetNillableSubjectType sets the "subject_type" field if the given value is not nil.
func (_u *TemplatePermissionUpdateOne) SetNillableSubjectType(v *templatepermission.SubjectType) *TemplatePermissionUpdateOne {
	if v != nil {
		_u.SetSubjectType(*v)
	}
	return _u
}

// SetSubjectID sets the "subject_id" field.
func (_u *TemplatePermissionUpdateOne) SetSubjectID(v string) *TemplatePermissionUpdateOne {
	_u.mutation.SetSubjectID(v)
	return _u
}

// SetNillableSubjectID sets the "subject_id" field if the given value is not nil.
func (_u *TemplatePermissionUpdateOne) SetNillableSubjectID(v *string) *TemplatePermissionUpdateOne {
	if v != nil {
		_u.SetSubjectID(*v)
	}
	return _u
}

// SetGrantedBy sets the "granted_by" field.
func (_u *TemplatePermissionUpdateOne) SetGrantedBy(v uint32) *TemplatePermissionUpdateOne {
	_u.mutation.ResetGrantedBy()
	_u.mutation.SetGrantedBy(v)
	return _u
}

// SetNillableGrantedBy sets the "granted_by" field if the given value is not nil.
func (_u *TemplatePermissionUpdateOne) SetNillableGrantedBy(v *uint32) *TemplatePermissionUpdateOne {
	if v != nil {
		_u.SetGrantedBy(*v)
	}
	return _u
}

// AddGrantedBy adds value to the "granted_by" field.
func (_u *TemplatePermissionUpdateOne) AddGrantedBy(v int32) *TemplatePermissionUpdateOne {
	_u.mutation.AddGrantedBy(v)
	return _u
}

// ClearGrantedBy clears the value of the "granted_by" field.
func (_u *TemplatePermissionUpdateOne) ClearGrantedBy() *TemplatePermissionUpdateOne {
	_u.mutation.ClearGrantedBy()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *TemplatePermissionUpdateOne) SetExpiresAt(v time.Time) *TemplatePermissionUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *TemplatePermissionUpdateOne) SetNillableExpiresAt(v *time.Time) *TemplatePermissionUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *TemplatePermissionUpdateOne) ClearExpiresAt() *TemplatePermissionUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// Mutation returns the TemplatePermissionMutation object of the builder.
func (_u *TemplatePermissionUpdateOne) Mutation() *TemplatePermissionMutation {
	return _u.mutation
}

// Where appends a list predicates to the TemplatePermissionUpdate builder.
func (_u *TemplatePermissionUpdateOne) Where(ps ...predicate.TemplatePermission) *TemplatePermissionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TemplatePermissionUpdateOne) Select(field string, fields ...string) *TemplatePermissionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TemplatePermission entity.
func (_u *TemplatePermissionUpdateOne) Save(ctx context.Context) (*TemplatePermission, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TemplatePermissionUpdateOne) SaveX(ctx context.Context) *TemplatePermission {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TemplatePermissionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TemplatePermissionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TemplatePermissionUpdateOne) check() error {
	if v, ok := _u.mutation.ResourceType(); ok {
		if err := templatepermission.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "TemplatePermission.resource_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResourceID(); ok {
		if err := templatepermission.ResourceIDValidator(v); err != nil {
			return &ValidationError{Name: "resource_id", err: fmt.Errorf(`ent: validator failed for field "TemplatePermission.resource_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Relation(); ok {
		if err := templatepermission.RelationValidator(v); err != nil {
			return &ValidationError{Name: "relation", err: fmt.Errorf(`ent: validator failed for field "TemplatePermission.relation": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SubjectType(); ok {
		if err := templatepermission.SubjectTypeValidator(v); err != nil {
			return &ValidationError{Name: "subject_type", err: fmt.Errorf(`ent: validator failed for field "TemplatePermission.subject_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SubjectID(); ok {
		if err := templatepermission.SubjectIDValidator(v); err != nil {
			return &ValidationError{Name: "subject_id", err: fmt.Errorf(`ent: validator failed for field "TemplatePermission.subject_id": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *TemplatePermissionUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TemplatePermissionUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *TemplatePermissionUpdateOne) sqlSave(ctx context.Context) (_node *TemplatePermission, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(templatepermission.Table, templatepermission.Columns, sqlgraph.NewFieldSpec(templatepermission.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TemplatePermission.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, templatepermission.FieldID)
		for _, f := range fields {
			if !templatepermission.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != templatepermission.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(templatepermission.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(templatepermission.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(templatepermission.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(templatepermission.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(templatepermission.FieldDeleteTime, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(templatepermission.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.ResourceType(); ok {
		_spec.SetField(templatepermission.FieldResourceType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ResourceID(); ok {
		_spec.SetField(templatepermission.FieldResourceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Relation(); ok {
		_spec.SetField(templatepermission.FieldRelation, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SubjectType(); ok {
		_spec.SetField(templatepermission.FieldSubjectType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SubjectID(); ok {
		_spec.SetField(templatepermission.FieldSubjectID, field.TypeString, value)
	}
	if value, ok := _u.mutation.GrantedBy(); ok {
		_spec.SetField(templatepermission.FieldGrantedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedGrantedBy(); ok {
		_spec.AddField(templatepermission.FieldGrantedBy, field.TypeUint32, value)
	}
	if _u.mutation.GrantedByCleared() {
		_spec.ClearField(templatepermission.FieldGrantedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(templatepermission.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(templatepermission.FieldExpiresAt, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &TemplatePermission{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{templatepermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
