// Code generated by ent, DO NOT EDIT.

package templatepermission

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/go-tangra/go-tangra-notification/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldLTE(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldEQ(FieldUpdateTime, v))
}

// DeleteTime applies equality check predicate on the "delete_time" field. It's identical to DeleteTimeEQ.
func DeleteTime(v time.Time) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldEQ(FieldDeleteTime, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uint32) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldEQ(FieldTenantID, v))
}

// ResourceID applies equality check predicate on the "resource_id" field. It's identical to ResourceIDEQ.
func ResourceID(v string) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldEQ(FieldResourceID, v))
}

// SubjectID applies equality check predicate on the "subject_id" field. It's identical to SubjectIDEQ.
func SubjectID(v string) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldEQ(FieldSubjectID, v))
}

// GrantedBy applies equality check predicate on the "granted_by" field. It's identical to GrantedByEQ.
func GrantedBy(v uint32) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldEQ(FieldGrantedBy, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldEQ(FieldExpiresAt, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldLTE(FieldCreateTime, v))
}

// CreateTimeIsNil applies the IsNil predicate on the "create_time" field.
func CreateTimeIsNil() predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldIsNull(FieldCreateTime))
}

// CreateTimeNotNil applies the NotNil predicate on the "create_time" field.
func CreateTimeNotNil() predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldNotNull(FieldCreateTime))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldLTE(FieldUpdateTime, v))
}

// UpdateTimeIsNil applies the IsNil predicate on the "update_time" field.
func UpdateTimeIsNil() predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldIsNull(FieldUpdateTime))
}

// UpdateTimeNotNil applies the NotNil predicate on the "update_time" field.
func UpdateTimeNotNil() predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldNotNull(FieldUpdateTime))
}

// DeleteTimeEQ applies the EQ predicate on the "delete_time" field.
func DeleteTimeEQ(v time.Time) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldEQ(FieldDeleteTime, v))
}

// DeleteTimeNEQ applies the NEQ predicate on the "delete_time" field.
func DeleteTimeNEQ(v time.Time) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldNEQ(FieldDeleteTime, v))
}

// DeleteTimeIn applies the In predicate on the "delete_time" field.
func DeleteTimeIn(vs ...time.Time) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldIn(FieldDeleteTime, vs...))
}

// DeleteTimeNotIn applies the NotIn predicate on the "delete_time" field.
func DeleteTimeNotIn(vs ...time.Time) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldNotIn(FieldDeleteTime, vs...))
}

// DeleteTimeGT applies the GT predicate on the "delete_time" field.
func DeleteTimeGT(v time.Time) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldGT(FieldDeleteTime, v))
}

// DeleteTimeGTE applies the GTE predicate on the "delete_time" field.
func DeleteTimeGTE(v time.Time) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldGTE(FieldDeleteTime, v))
}

// DeleteTimeLT applies the LT predicate on the "delete_time" field.
func DeleteTimeLT(v time.Time) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldLT(FieldDeleteTime, v))
}

// DeleteTimeLTE applies the LTE predicate on the "delete_time" field.
func DeleteTimeLTE(v time.Time) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldLTE(FieldDeleteTime, v))
}

// DeleteTimeIsNil applies the IsNil predicate on the "delete_time" field.
func DeleteTimeIsNil() predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldIsNull(FieldDeleteTime))
}

// DeleteTimeNotNil applies the NotNil predicate on the "delete_time" field.
func DeleteTimeNotNil() predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldNotNull(FieldDeleteTime))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uint32) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uint32) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uint32) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uint32) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uint32) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uint32) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uint32) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uint32) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldNotNull(FieldTenantID))
}

// ResourceTypeEQ applies the EQ predicate on the "resource_type" field.
func ResourceTypeEQ(v ResourceType) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldEQ(FieldResourceType, v))
}

// ResourceTypeNEQ applies the NEQ predicate on the "resource_type" field.
func ResourceTypeNEQ(v ResourceType) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldNEQ(FieldResourceType, v))
}

// ResourceTypeIn applies the In predicate on the "resource_type" field.
func ResourceTypeIn(vs ...ResourceType) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldIn(FieldResourceType, vs...))
}

// ResourceTypeNotIn applies the NotIn predicate on the "resource_type" field.
func ResourceTypeNotIn(vs ...ResourceType) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldNotIn(FieldResourceType, vs...))
}

// ResourceIDEQ applies the EQ predicate on the "resource_id" field.
func ResourceIDEQ(v string) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldEQ(FieldResourceID, v))
}

// ResourceIDNEQ applies the NEQ predicate on the "resource_id" field.
func ResourceIDNEQ(v string) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldNEQ(FieldResourceID, v))
}

// ResourceIDIn applies the In predicate on the "resource_id" field.
func ResourceIDIn(vs ...string) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldIn(FieldResourceID, vs...))
}

// ResourceIDNotIn applies the NotIn predicate on the "resource_id" field.
func ResourceIDNotIn(vs ...string) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldNotIn(FieldResourceID, vs...))
}

// ResourceIDGT applies the GT predicate on the "resource_id" field.
func ResourceIDGT(v string) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldGT(FieldResourceID, v))
}

// ResourceIDGTE applies the GTE predicate on the "resource_id" field.
func ResourceIDGTE(v string) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldGTE(FieldResourceID, v))
}

// ResourceIDLT applies the LT predicate on the "resource_id" field.
func ResourceIDLT(v string) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldLT(FieldResourceID, v))
}

// ResourceIDLTE applies the LTE predicate on the "resource_id" field.
func ResourceIDLTE(v string) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldLTE(FieldResourceID, v))
}

// ResourceIDContains applies the Contains predicate on the "resource_id" field.
func ResourceIDContains(v string) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldContains(FieldResourceID, v))
}

// ResourceIDHasPrefix applies the HasPrefix predicate on the "resource_id" field.
func ResourceIDHasPrefix(v string) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldHasPrefix(FieldResourceID, v))
}

// ResourceIDHasSuffix applies the HasSuffix predicate on the "resource_id" field.
func ResourceIDHasSuffix(v string) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldHasSuffix(FieldResourceID, v))
}

// ResourceIDEqualFold applies the EqualFold predicate on the "resource_id" field.
func ResourceIDEqualFold(v string) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldEqualFold(FieldResourceID, v))
}

// ResourceIDContainsFold applies the ContainsFold predicate on the "resource_id" field.
func ResourceIDContainsFold(v string) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldContainsFold(FieldResourceID, v))
}

// RelationEQ applies the EQ predicate on the "relation" field.
func RelationEQ(v Relation) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldEQ(FieldRelation, v))
}

// RelationNEQ applies the NEQ predicate on the "relation" field.
func RelationNEQ(v Relation) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldNEQ(FieldRelation, v))
}

// RelationIn applies the In predicate on the "relation" field.
func RelationIn(vs ...Relation) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldIn(FieldRelation, vs...))
}

// RelationNotIn applies the NotIn predicate on the "relation" field.
func RelationNotIn(vs ...Relation) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldNotIn(FieldRelation, vs...))
}

// SubjectTypeEQ applies the EQ predicate on the "subject_type" field.
func SubjectTypeEQ(v SubjectType) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldEQ(FieldSubjectType, v))
}

// SubjectTypeNEQ applies the NEQ predicate on the "subject_type" field.
func SubjectTypeNEQ(v SubjectType) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldNEQ(FieldSubjectType, v))
}

// SubjectTypeIn applies the In predicate on the "subject_type" field.
func SubjectTypeIn(vs ...SubjectType) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldIn(FieldSubjectType, vs...))
}

// SubjectTypeNotIn applies the NotIn predicate on the "subject_type" field.
func SubjectTypeNotIn(vs ...SubjectType) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldNotIn(FieldSubjectType, vs...))
}

// SubjectIDEQ applies the EQ predicate on the "subject_id" field.
func SubjectIDEQ(v string) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldEQ(FieldSubjectID, v))
}

// SubjectIDNEQ applies the NEQ predicate on the "subject_id" field.
func SubjectIDNEQ(v string) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldNEQ(FieldSubjectID, v))
}

// SubjectIDIn applies the In predicate on the "subject_id" field.
func SubjectIDIn(vs ...string) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldIn(FieldSubjectID, vs...))
}

// SubjectIDNotIn applies the NotIn predicate on the "subject_id" field.
func SubjectIDNotIn(vs ...string) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldNotIn(FieldSubjectID, vs...))
}

// SubjectIDGT applies the GT predicate on the "subject_id" field.
func SubjectIDGT(v string) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldGT(FieldSubjectID, v))
}

// SubjectIDGTE applies the GTE predicate on the "subject_id" field.
func SubjectIDGTE(v string) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldGTE(FieldSubjectID, v))
}

// SubjectIDLT applies the LT predicate on the "subject_id" field.
func SubjectIDLT(v string) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldLT(FieldSubjectID, v))
}

// SubjectIDLTE applies the LTE predicate on the "subject_id" field.
func SubjectIDLTE(v string) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldLTE(FieldSubjectID, v))
}

// SubjectIDContains applies the Contains predicate on the "subject_id" field.
func SubjectIDContains(v string) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldContains(FieldSubjectID, v))
}

// SubjectIDHasPrefix applies the HasPrefix predicate on the "subject_id" field.
func SubjectIDHasPrefix(v string) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldHasPrefix(FieldSubjectID, v))
}

// SubjectIDHasSuffix applies the HasSuffix predicate on the "subject_id" field.
func SubjectIDHasSuffix(v string) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldHasSuffix(FieldSubjectID, v))
}

// SubjectIDEqualFold applies the EqualFold predicate on the "subject_id" field.
func SubjectIDEqualFold(v string) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldEqualFold(FieldSubjectID, v))
}

// SubjectIDContainsFold applies the ContainsFold predicate on the "subject_id" field.
func SubjectIDContainsFold(v string) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldContainsFold(FieldSubjectID, v))
}

// GrantedByEQ applies the EQ predicate on the "granted_by" field.
func GrantedByEQ(v uint32) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldEQ(FieldGrantedBy, v))
}

// GrantedByNEQ applies the NEQ predicate on the "granted_by" field.
func GrantedByNEQ(v uint32) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldNEQ(FieldGrantedBy, v))
}

// GrantedByIn applies the In predicate on the "granted_by" field.
func GrantedByIn(vs ...uint32) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldIn(FieldGrantedBy, vs...))
}

// GrantedByNotIn applies the NotIn predicate on the "granted_by" field.
func GrantedByNotIn(vs ...uint32) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldNotIn(FieldGrantedBy, vs...))
}

// GrantedByGT applies the GT predicate on the "granted_by" field.
func GrantedByGT(v uint32) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldGT(FieldGrantedBy, v))
}

// GrantedByGTE applies the GTE predicate on the "granted_by" field.
func GrantedByGTE(v uint32) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldGTE(FieldGrantedBy, v))
}

// GrantedByLT applies the LT predicate on the "granted_by" field.
func GrantedByLT(v uint32) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldLT(FieldGrantedBy, v))
}

// GrantedByLTE applies the LTE predicate on the "granted_by" field.
func GrantedByLTE(v uint32) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldLTE(FieldGrantedBy, v))
}

// GrantedByIsNil applies the IsNil predicate on the "granted_by" field.
func GrantedByIsNil() predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldIsNull(FieldGrantedBy))
}

// GrantedByNotNil applies the NotNil predicate on the "granted_by" field.
func GrantedByNotNil() predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldNotNull(FieldGrantedBy))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.FieldNotNull(FieldExpiresAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TemplatePermission) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TemplatePermission) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TemplatePermission) predicate.TemplatePermission {
	return predicate.TemplatePermission(sql.NotPredicates(p))
}
