// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// NotificationChannelsColumns holds the columns for the "notification_channels" table.
	NotificationChannelsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Comment: "UUID primary key"},
		{Name: "create_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "update_by", Type: field.TypeUint32, Nullable: true, Comment: "更新者ID"},
		{Name: "create_time", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "update_time", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "delete_time", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID", Default: 0},
		{Name: "name", Type: field.TypeString, Size: 255, Comment: "Channel display name"},
		{Name: "type", Type: field.TypeEnum, Comment: "Channel type", Enums: []string{"EMAIL", "SMS", "SLACK", "SSE"}},
		{Name: "config", Type: field.TypeString, Size: 2147483647, Comment: "JSON-encoded channel configuration", Default: "{}"},
		{Name: "enabled", Type: field.TypeBool, Comment: "Whether the channel is active", Default: true},
		{Name: "is_default", Type: field.TypeBool, Comment: "Whether this is the default channel for its type", Default: false},
	}
	// NotificationChannelsTable holds the schema information for the "notification_channels" table.
	NotificationChannelsTable = &schema.Table{
		Name:       "notification_channels",
		Columns:    NotificationChannelsColumns,
		PrimaryKey: []*schema.Column{NotificationChannelsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "channel_tenant_id_name",
				Unique:  true,
				Columns: []*schema.Column{NotificationChannelsColumns[6], NotificationChannelsColumns[7]},
			},
			{
				Name:    "channel_tenant_id_type",
				Unique:  false,
				Columns: []*schema.Column{NotificationChannelsColumns[6], NotificationChannelsColumns[8]},
			},
			{
				Name:    "channel_tenant_id_type_is_default",
				Unique:  false,
				Columns: []*schema.Column{NotificationChannelsColumns[6], NotificationChannelsColumns[8], NotificationChannelsColumns[11]},
			},
			{
				Name:    "channel_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{NotificationChannelsColumns[6]},
			},
		},
	}
	// NotificationLogsColumns holds the columns for the "notification_logs" table.
	NotificationLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Comment: "UUID primary key"},
		{Name: "create_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "create_time", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "update_time", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "delete_time", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID", Default: 0},
		{Name: "channel_id", Type: field.TypeString, Size: 36, Comment: "FK to notification_channels"},
		{Name: "channel_type", Type: field.TypeEnum, Comment: "Channel type used", Enums: []string{"EMAIL", "SMS", "SLACK", "SSE"}},
		{Name: "template_id", Type: field.TypeString, Size: 36, Comment: "FK to notification_templates"},
		{Name: "recipient", Type: field.TypeString, Size: 512, Comment: "Recipient address"},
		{Name: "rendered_subject", Type: field.TypeString, Size: 1024, Comment: "Rendered subject", Default: ""},
		{Name: "rendered_body", Type: field.TypeString, Size: 2147483647, Comment: "Rendered body", Default: ""},
		{Name: "status", Type: field.TypeEnum, Comment: "Delivery status", Enums: []string{"PENDING", "SENT", "FAILED"}, Default: "PENDING"},
		{Name: "error_message", Type: field.TypeString, Size: 2147483647, Comment: "Error message if delivery failed", Default: ""},
		{Name: "sent_at", Type: field.TypeTime, Nullable: true, Comment: "When the notification was sent"},
	}
	// NotificationLogsTable holds the schema information for the "notification_logs" table.
	NotificationLogsTable = &schema.Table{
		Name:       "notification_logs",
		Columns:    NotificationLogsColumns,
		PrimaryKey: []*schema.Column{NotificationLogsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "notificationlog_tenant_id_channel_type",
				Unique:  false,
				Columns: []*schema.Column{NotificationLogsColumns[5], NotificationLogsColumns[7]},
			},
			{
				Name:    "notificationlog_tenant_id_status",
				Unique:  false,
				Columns: []*schema.Column{NotificationLogsColumns[5], NotificationLogsColumns[12]},
			},
			{
				Name:    "notificationlog_tenant_id_recipient",
				Unique:  false,
				Columns: []*schema.Column{NotificationLogsColumns[5], NotificationLogsColumns[9]},
			},
			{
				Name:    "notificationlog_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{NotificationLogsColumns[5]},
			},
			{
				Name:    "notificationlog_channel_id",
				Unique:  false,
				Columns: []*schema.Column{NotificationLogsColumns[6]},
			},
			{
				Name:    "notificationlog_template_id",
				Unique:  false,
				Columns: []*schema.Column{NotificationLogsColumns[8]},
			},
		},
	}
	// NotificationTemplatesColumns holds the columns for the "notification_templates" table.
	NotificationTemplatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Comment: "UUID primary key"},
		{Name: "create_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "update_by", Type: field.TypeUint32, Nullable: true, Comment: "更新者ID"},
		{Name: "create_time", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "update_time", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "delete_time", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID", Default: 0},
		{Name: "name", Type: field.TypeString, Size: 255, Comment: "Template name"},
		{Name: "channel_id", Type: field.TypeString, Size: 36, Comment: "References notification_channels.id"},
		{Name: "subject", Type: field.TypeString, Size: 1024, Comment: "Subject template (Go text/template)"},
		{Name: "body", Type: field.TypeString, Size: 2147483647, Comment: "Body template (Go text/template or html/template for email)"},
		{Name: "variables", Type: field.TypeString, Size: 2048, Comment: "Comma-separated list of expected variable names", Default: ""},
		{Name: "is_default", Type: field.TypeBool, Comment: "Whether this is the default template for its channel", Default: false},
	}
	// NotificationTemplatesTable holds the schema information for the "notification_templates" table.
	NotificationTemplatesTable = &schema.Table{
		Name:       "notification_templates",
		Columns:    NotificationTemplatesColumns,
		PrimaryKey: []*schema.Column{NotificationTemplatesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "template_tenant_id_name",
				Unique:  true,
				Columns: []*schema.Column{NotificationTemplatesColumns[6], NotificationTemplatesColumns[7]},
			},
			{
				Name:    "template_tenant_id_channel_id",
				Unique:  false,
				Columns: []*schema.Column{NotificationTemplatesColumns[6], NotificationTemplatesColumns[8]},
			},
			{
				Name:    "template_tenant_id_channel_id_is_default",
				Unique:  false,
				Columns: []*schema.Column{NotificationTemplatesColumns[6], NotificationTemplatesColumns[8], NotificationTemplatesColumns[12]},
			},
			{
				Name:    "template_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{NotificationTemplatesColumns[6]},
			},
		},
	}
	// NotificationTemplatePermissionsColumns holds the columns for the "notification_template_permissions" table.
	NotificationTemplatePermissionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "create_time", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "update_time", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "delete_time", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID", Default: 0},
		{Name: "resource_type", Type: field.TypeEnum, Comment: "Type of resource (template or channel)", Enums: []string{"RESOURCE_TYPE_UNSPECIFIED", "RESOURCE_TYPE_TEMPLATE", "RESOURCE_TYPE_CHANNEL"}},
		{Name: "resource_id", Type: field.TypeString, Size: 36, Comment: "ID of the resource (UUID)"},
		{Name: "relation", Type: field.TypeEnum, Comment: "Permission level (owner, editor, viewer, sharer)", Enums: []string{"RELATION_UNSPECIFIED", "RELATION_OWNER", "RELATION_EDITOR", "RELATION_VIEWER", "RELATION_SHARER"}},
		{Name: "subject_type", Type: field.TypeEnum, Comment: "Type of subject (user, role, or mTLS client)", Enums: []string{"SUBJECT_TYPE_UNSPECIFIED", "SUBJECT_TYPE_USER", "SUBJECT_TYPE_ROLE", "SUBJECT_TYPE_CLIENT"}},
		{Name: "subject_id", Type: field.TypeString, Size: 255, Comment: "ID of the user, role, or mTLS client name"},
		{Name: "granted_by", Type: field.TypeUint32, Nullable: true, Comment: "User ID who granted this permission"},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true, Comment: "Optional expiration time for temporary access"},
	}
	// NotificationTemplatePermissionsTable holds the schema information for the "notification_template_permissions" table.
	NotificationTemplatePermissionsTable = &schema.Table{
		Name:       "notification_template_permissions",
		Columns:    NotificationTemplatePermissionsColumns,
		PrimaryKey: []*schema.Column{NotificationTemplatePermissionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "templatepermission_tenant_id_resource_type_resource_id_relation_subject_type_subject_id",
				Unique:  true,
				Columns: []*schema.Column{NotificationTemplatePermissionsColumns[4], NotificationTemplatePermissionsColumns[5], NotificationTemplatePermissionsColumns[6], NotificationTemplatePermissionsColumns[7], NotificationTemplatePermissionsColumns[8], NotificationTemplatePermissionsColumns[9]},
			},
			{
				Name:    "templatepermission_tenant_id_resource_type_resource_id",
				Unique:  false,
				Columns: []*schema.Column{NotificationTemplatePermissionsColumns[4], NotificationTemplatePermissionsColumns[5], NotificationTemplatePermissionsColumns[6]},
			},
			{
				Name:    "templatepermission_tenant_id_subject_type_subject_id",
				Unique:  false,
				Columns: []*schema.Column{NotificationTemplatePermissionsColumns[4], NotificationTemplatePermissionsColumns[8], NotificationTemplatePermissionsColumns[9]},
			},
			{
				Name:    "templatepermission_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{NotificationTemplatePermissionsColumns[4]},
			},
			{
				Name:    "templatepermission_expires_at",
				Unique:  false,
				Columns: []*schema.Column{NotificationTemplatePermissionsColumns[11]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		NotificationChannelsTable,
		NotificationLogsTable,
		NotificationTemplatesTable,
		NotificationTemplatePermissionsTable,
	}
)

func init() {
	NotificationChannelsTable.Annotation = &entsql.Annotation{
		Table: "notification_channels",
	}
	NotificationLogsTable.Annotation = &entsql.Annotation{
		Table: "notification_logs",
	}
	NotificationTemplatesTable.Annotation = &entsql.Annotation{
		Table: "notification_templates",
	}
	NotificationTemplatePermissionsTable.Annotation = &entsql.Annotation{
		Table: "notification_template_permissions",
	}
}
