// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-tangra/go-tangra-notification/internal/cert"
	"github.com/go-tangra/go-tangra-notification/internal/data"
	"github.com/go-tangra/go-tangra-notification/internal/server"
	"github.com/go-tangra/go-tangra-notification/internal/service"
	"github.com/tx7do/kratos-bootstrap/bootstrap"
)

// Injectors from wire.go:

func initApp(context *bootstrap.Context) (*kratos.App, func(), error) {
	certManager, err := cert.NewCertManager(context)
	if err != nil {
		return nil, nil, err
	}
	entClient, cleanup, err := data.NewEntClient(context)
	if err != nil {
		return nil, nil, err
	}
	channelRepo := data.NewChannelRepo(context, entClient)
	channelService := service.NewChannelService(context, channelRepo)
	templateRepo := data.NewTemplateRepo(context, entClient)
	templateService := service.NewTemplateService(context, templateRepo)
	notificationLogRepo := data.NewNotificationLogRepo(context, entClient)
	notificationService := service.NewNotificationService(context, channelRepo, templateRepo, notificationLogRepo)
	grpcServer := server.NewGRPCServer(context, certManager, channelService, templateService, notificationService)
	app := newApp(context, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
