// Code generated by ent, DO NOT EDIT.

package notificationlog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/go-tangra/go-tangra-notification/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldContainsFold(FieldID, id))
}

// CreateBy applies equality check predicate on the "create_by" field. It's identical to CreateByEQ.
func CreateBy(v uint32) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldEQ(FieldCreateBy, v))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldEQ(FieldUpdateTime, v))
}

// DeleteTime applies equality check predicate on the "delete_time" field. It's identical to DeleteTimeEQ.
func DeleteTime(v time.Time) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldEQ(FieldDeleteTime, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uint32) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldEQ(FieldTenantID, v))
}

// ChannelID applies equality check predicate on the "channel_id" field. It's identical to ChannelIDEQ.
func ChannelID(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldEQ(FieldChannelID, v))
}

// TemplateID applies equality check predicate on the "template_id" field. It's identical to TemplateIDEQ.
func TemplateID(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldEQ(FieldTemplateID, v))
}

// Recipient applies equality check predicate on the "recipient" field. It's identical to RecipientEQ.
func Recipient(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldEQ(FieldRecipient, v))
}

// RenderedSubject applies equality check predicate on the "rendered_subject" field. It's identical to RenderedSubjectEQ.
func RenderedSubject(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldEQ(FieldRenderedSubject, v))
}

// RenderedBody applies equality check predicate on the "rendered_body" field. It's identical to RenderedBodyEQ.
func RenderedBody(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldEQ(FieldRenderedBody, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldEQ(FieldErrorMessage, v))
}

// SentAt applies equality check predicate on the "sent_at" field. It's identical to SentAtEQ.
func SentAt(v time.Time) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldEQ(FieldSentAt, v))
}

// CreateByEQ applies the EQ predicate on the "create_by" field.
func CreateByEQ(v uint32) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldEQ(FieldCreateBy, v))
}

// CreateByNEQ applies the NEQ predicate on the "create_by" field.
func CreateByNEQ(v uint32) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldNEQ(FieldCreateBy, v))
}

// CreateByIn applies the In predicate on the "create_by" field.
func CreateByIn(vs ...uint32) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldIn(FieldCreateBy, vs...))
}

// CreateByNotIn applies the NotIn predicate on the "create_by" field.
func CreateByNotIn(vs ...uint32) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldNotIn(FieldCreateBy, vs...))
}

// CreateByGT applies the GT predicate on the "create_by" field.
func CreateByGT(v uint32) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldGT(FieldCreateBy, v))
}

// CreateByGTE applies the GTE predicate on the "create_by" field.
func CreateByGTE(v uint32) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldGTE(FieldCreateBy, v))
}

// CreateByLT applies the LT predicate on the "create_by" field.
func CreateByLT(v uint32) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldLT(FieldCreateBy, v))
}

// CreateByLTE applies the LTE predicate on the "create_by" field.
func CreateByLTE(v uint32) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldLTE(FieldCreateBy, v))
}

// CreateByIsNil applies the IsNil predicate on the "create_by" field.
func CreateByIsNil() predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldIsNull(FieldCreateBy))
}

// CreateByNotNil applies the NotNil predicate on the "create_by" field.
func CreateByNotNil() predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldNotNull(FieldCreateBy))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldLTE(FieldCreateTime, v))
}

// CreateTimeIsNil applies the IsNil predicate on the "create_time" field.
func CreateTimeIsNil() predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldIsNull(FieldCreateTime))
}

// CreateTimeNotNil applies the NotNil predicate on the "create_time" field.
func CreateTimeNotNil() predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldNotNull(FieldCreateTime))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldLTE(FieldUpdateTime, v))
}

// UpdateTimeIsNil applies the IsNil predicate on the "update_time" field.
func UpdateTimeIsNil() predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldIsNull(FieldUpdateTime))
}

// UpdateTimeNotNil applies the NotNil predicate on the "update_time" field.
func UpdateTimeNotNil() predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldNotNull(FieldUpdateTime))
}

// DeleteTimeEQ applies the EQ predicate on the "delete_time" field.
func DeleteTimeEQ(v time.Time) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldEQ(FieldDeleteTime, v))
}

// DeleteTimeNEQ applies the NEQ predicate on the "delete_time" field.
func DeleteTimeNEQ(v time.Time) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldNEQ(FieldDeleteTime, v))
}

// DeleteTimeIn applies the In predicate on the "delete_time" field.
func DeleteTimeIn(vs ...time.Time) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldIn(FieldDeleteTime, vs...))
}

// DeleteTimeNotIn applies the NotIn predicate on the "delete_time" field.
func DeleteTimeNotIn(vs ...time.Time) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldNotIn(FieldDeleteTime, vs...))
}

// DeleteTimeGT applies the GT predicate on the "delete_time" field.
func DeleteTimeGT(v time.Time) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldGT(FieldDeleteTime, v))
}

// DeleteTimeGTE applies the GTE predicate on the "delete_time" field.
func DeleteTimeGTE(v time.Time) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldGTE(FieldDeleteTime, v))
}

// DeleteTimeLT applies the LT predicate on the "delete_time" field.
func DeleteTimeLT(v time.Time) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldLT(FieldDeleteTime, v))
}

// DeleteTimeLTE applies the LTE predicate on the "delete_time" field.
func DeleteTimeLTE(v time.Time) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldLTE(FieldDeleteTime, v))
}

// DeleteTimeIsNil applies the IsNil predicate on the "delete_time" field.
func DeleteTimeIsNil() predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldIsNull(FieldDeleteTime))
}

// DeleteTimeNotNil applies the NotNil predicate on the "delete_time" field.
func DeleteTimeNotNil() predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldNotNull(FieldDeleteTime))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uint32) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uint32) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uint32) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uint32) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uint32) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uint32) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uint32) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uint32) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldNotNull(FieldTenantID))
}

// ChannelIDEQ applies the EQ predicate on the "channel_id" field.
func ChannelIDEQ(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldEQ(FieldChannelID, v))
}

// ChannelIDNEQ applies the NEQ predicate on the "channel_id" field.
func ChannelIDNEQ(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldNEQ(FieldChannelID, v))
}

// ChannelIDIn applies the In predicate on the "channel_id" field.
func ChannelIDIn(vs ...string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldIn(FieldChannelID, vs...))
}

// ChannelIDNotIn applies the NotIn predicate on the "channel_id" field.
func ChannelIDNotIn(vs ...string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldNotIn(FieldChannelID, vs...))
}

// ChannelIDGT applies the GT predicate on the "channel_id" field.
func ChannelIDGT(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldGT(FieldChannelID, v))
}

// ChannelIDGTE applies the GTE predicate on the "channel_id" field.
func ChannelIDGTE(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldGTE(FieldChannelID, v))
}

// ChannelIDLT applies the LT predicate on the "channel_id" field.
func ChannelIDLT(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldLT(FieldChannelID, v))
}

// ChannelIDLTE applies the LTE predicate on the "channel_id" field.
func ChannelIDLTE(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldLTE(FieldChannelID, v))
}

// ChannelIDContains applies the Contains predicate on the "channel_id" field.
func ChannelIDContains(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldContains(FieldChannelID, v))
}

// ChannelIDHasPrefix applies the HasPrefix predicate on the "channel_id" field.
func ChannelIDHasPrefix(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldHasPrefix(FieldChannelID, v))
}

// ChannelIDHasSuffix applies the HasSuffix predicate on the "channel_id" field.
func ChannelIDHasSuffix(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldHasSuffix(FieldChannelID, v))
}

// ChannelIDEqualFold applies the EqualFold predicate on the "channel_id" field.
func ChannelIDEqualFold(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldEqualFold(FieldChannelID, v))
}

// ChannelIDContainsFold applies the ContainsFold predicate on the "channel_id" field.
func ChannelIDContainsFold(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldContainsFold(FieldChannelID, v))
}

// ChannelTypeEQ applies the EQ predicate on the "channel_type" field.
func ChannelTypeEQ(v ChannelType) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldEQ(FieldChannelType, v))
}

// ChannelTypeNEQ applies the NEQ predicate on the "channel_type" field.
func ChannelTypeNEQ(v ChannelType) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldNEQ(FieldChannelType, v))
}

// ChannelTypeIn applies the In predicate on the "channel_type" field.
func ChannelTypeIn(vs ...ChannelType) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldIn(FieldChannelType, vs...))
}

// ChannelTypeNotIn applies the NotIn predicate on the "channel_type" field.
func ChannelTypeNotIn(vs ...ChannelType) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldNotIn(FieldChannelType, vs...))
}

// TemplateIDEQ applies the EQ predicate on the "template_id" field.
func TemplateIDEQ(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldEQ(FieldTemplateID, v))
}

// TemplateIDNEQ applies the NEQ predicate on the "template_id" field.
func TemplateIDNEQ(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldNEQ(FieldTemplateID, v))
}

// TemplateIDIn applies the In predicate on the "template_id" field.
func TemplateIDIn(vs ...string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldIn(FieldTemplateID, vs...))
}

// TemplateIDNotIn applies the NotIn predicate on the "template_id" field.
func TemplateIDNotIn(vs ...string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldNotIn(FieldTemplateID, vs...))
}

// TemplateIDGT applies the GT predicate on the "template_id" field.
func TemplateIDGT(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldGT(FieldTemplateID, v))
}

// TemplateIDGTE applies the GTE predicate on the "template_id" field.
func TemplateIDGTE(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldGTE(FieldTemplateID, v))
}

// TemplateIDLT applies the LT predicate on the "template_id" field.
func TemplateIDLT(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldLT(FieldTemplateID, v))
}

// TemplateIDLTE applies the LTE predicate on the "template_id" field.
func TemplateIDLTE(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldLTE(FieldTemplateID, v))
}

// TemplateIDContains applies the Contains predicate on the "template_id" field.
func TemplateIDContains(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldContains(FieldTemplateID, v))
}

// TemplateIDHasPrefix applies the HasPrefix predicate on the "template_id" field.
func TemplateIDHasPrefix(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldHasPrefix(FieldTemplateID, v))
}

// TemplateIDHasSuffix applies the HasSuffix predicate on the "template_id" field.
func TemplateIDHasSuffix(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldHasSuffix(FieldTemplateID, v))
}

// TemplateIDEqualFold applies the EqualFold predicate on the "template_id" field.
func TemplateIDEqualFold(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldEqualFold(FieldTemplateID, v))
}

// TemplateIDContainsFold applies the ContainsFold predicate on the "template_id" field.
func TemplateIDContainsFold(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldContainsFold(FieldTemplateID, v))
}

// RecipientEQ applies the EQ predicate on the "recipient" field.
func RecipientEQ(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldEQ(FieldRecipient, v))
}

// RecipientNEQ applies the NEQ predicate on the "recipient" field.
func RecipientNEQ(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldNEQ(FieldRecipient, v))
}

// RecipientIn applies the In predicate on the "recipient" field.
func RecipientIn(vs ...string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldIn(FieldRecipient, vs...))
}

// RecipientNotIn applies the NotIn predicate on the "recipient" field.
func RecipientNotIn(vs ...string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldNotIn(FieldRecipient, vs...))
}

// RecipientGT applies the GT predicate on the "recipient" field.
func RecipientGT(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldGT(FieldRecipient, v))
}

// RecipientGTE applies the GTE predicate on the "recipient" field.
func RecipientGTE(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldGTE(FieldRecipient, v))
}

// RecipientLT applies the LT predicate on the "recipient" field.
func RecipientLT(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldLT(FieldRecipient, v))
}

// RecipientLTE applies the LTE predicate on the "recipient" field.
func RecipientLTE(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldLTE(FieldRecipient, v))
}

// RecipientContains applies the Contains predicate on the "recipient" field.
func RecipientContains(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldContains(FieldRecipient, v))
}

// RecipientHasPrefix applies the HasPrefix predicate on the "recipient" field.
func RecipientHasPrefix(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldHasPrefix(FieldRecipient, v))
}

// RecipientHasSuffix applies the HasSuffix predicate on the "recipient" field.
func RecipientHasSuffix(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldHasSuffix(FieldRecipient, v))
}

// RecipientEqualFold applies the EqualFold predicate on the "recipient" field.
func RecipientEqualFold(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldEqualFold(FieldRecipient, v))
}

// RecipientContainsFold applies the ContainsFold predicate on the "recipient" field.
func RecipientContainsFold(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldContainsFold(FieldRecipient, v))
}

// RenderedSubjectEQ applies the EQ predicate on the "rendered_subject" field.
func RenderedSubjectEQ(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldEQ(FieldRenderedSubject, v))
}

// RenderedSubjectNEQ applies the NEQ predicate on the "rendered_subject" field.
func RenderedSubjectNEQ(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldNEQ(FieldRenderedSubject, v))
}

// RenderedSubjectIn applies the In predicate on the "rendered_subject" field.
func RenderedSubjectIn(vs ...string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldIn(FieldRenderedSubject, vs...))
}

// RenderedSubjectNotIn applies the NotIn predicate on the "rendered_subject" field.
func RenderedSubjectNotIn(vs ...string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldNotIn(FieldRenderedSubject, vs...))
}

// RenderedSubjectGT applies the GT predicate on the "rendered_subject" field.
func RenderedSubjectGT(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldGT(FieldRenderedSubject, v))
}

// RenderedSubjectGTE applies the GTE predicate on the "rendered_subject" field.
func RenderedSubjectGTE(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldGTE(FieldRenderedSubject, v))
}

// RenderedSubjectLT applies the LT predicate on the "rendered_subject" field.
func RenderedSubjectLT(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldLT(FieldRenderedSubject, v))
}

// RenderedSubjectLTE applies the LTE predicate on the "rendered_subject" field.
func RenderedSubjectLTE(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldLTE(FieldRenderedSubject, v))
}

// RenderedSubjectContains applies the Contains predicate on the "rendered_subject" field.
func RenderedSubjectContains(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldContains(FieldRenderedSubject, v))
}

// RenderedSubjectHasPrefix applies the HasPrefix predicate on the "rendered_subject" field.
func RenderedSubjectHasPrefix(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldHasPrefix(FieldRenderedSubject, v))
}

// RenderedSubjectHasSuffix applies the HasSuffix predicate on the "rendered_subject" field.
func RenderedSubjectHasSuffix(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldHasSuffix(FieldRenderedSubject, v))
}

// RenderedSubjectEqualFold applies the EqualFold predicate on the "rendered_subject" field.
func RenderedSubjectEqualFold(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldEqualFold(FieldRenderedSubject, v))
}

// RenderedSubjectContainsFold applies the ContainsFold predicate on the "rendered_subject" field.
func RenderedSubjectContainsFold(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldContainsFold(FieldRenderedSubject, v))
}

// RenderedBodyEQ applies the EQ predicate on the "rendered_body" field.
func RenderedBodyEQ(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldEQ(FieldRenderedBody, v))
}

// RenderedBodyNEQ applies the NEQ predicate on the "rendered_body" field.
func RenderedBodyNEQ(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldNEQ(FieldRenderedBody, v))
}

// RenderedBodyIn applies the In predicate on the "rendered_body" field.
func RenderedBodyIn(vs ...string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldIn(FieldRenderedBody, vs...))
}

// RenderedBodyNotIn applies the NotIn predicate on the "rendered_body" field.
func RenderedBodyNotIn(vs ...string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldNotIn(FieldRenderedBody, vs...))
}

// RenderedBodyGT applies the GT predicate on the "rendered_body" field.
func RenderedBodyGT(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldGT(FieldRenderedBody, v))
}

// RenderedBodyGTE applies the GTE predicate on the "rendered_body" field.
func RenderedBodyGTE(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldGTE(FieldRenderedBody, v))
}

// RenderedBodyLT applies the LT predicate on the "rendered_body" field.
func RenderedBodyLT(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldLT(FieldRenderedBody, v))
}

// RenderedBodyLTE applies the LTE predicate on the "rendered_body" field.
func RenderedBodyLTE(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldLTE(FieldRenderedBody, v))
}

// RenderedBodyContains applies the Contains predicate on the "rendered_body" field.
func RenderedBodyContains(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldContains(FieldRenderedBody, v))
}

// RenderedBodyHasPrefix applies the HasPrefix predicate on the "rendered_body" field.
func RenderedBodyHasPrefix(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldHasPrefix(FieldRenderedBody, v))
}

// RenderedBodyHasSuffix applies the HasSuffix predicate on the "rendered_body" field.
func RenderedBodyHasSuffix(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldHasSuffix(FieldRenderedBody, v))
}

// RenderedBodyEqualFold applies the EqualFold predicate on the "rendered_body" field.
func RenderedBodyEqualFold(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldEqualFold(FieldRenderedBody, v))
}

// RenderedBodyContainsFold applies the ContainsFold predicate on the "rendered_body" field.
func RenderedBodyContainsFold(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldContainsFold(FieldRenderedBody, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldNotIn(FieldStatus, vs...))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldContainsFold(FieldErrorMessage, v))
}

// SentAtEQ applies the EQ predicate on the "sent_at" field.
func SentAtEQ(v time.Time) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldEQ(FieldSentAt, v))
}

// SentAtNEQ applies the NEQ predicate on the "sent_at" field.
func SentAtNEQ(v time.Time) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldNEQ(FieldSentAt, v))
}

// SentAtIn applies the In predicate on the "sent_at" field.
func SentAtIn(vs ...time.Time) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldIn(FieldSentAt, vs...))
}

// SentAtNotIn applies the NotIn predicate on the "sent_at" field.
func SentAtNotIn(vs ...time.Time) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldNotIn(FieldSentAt, vs...))
}

// SentAtGT applies the GT predicate on the "sent_at" field.
func SentAtGT(v time.Time) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldGT(FieldSentAt, v))
}

// SentAtGTE applies the GTE predicate on the "sent_at" field.
func SentAtGTE(v time.Time) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldGTE(FieldSentAt, v))
}

// SentAtLT applies the LT predicate on the "sent_at" field.
func SentAtLT(v time.Time) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldLT(FieldSentAt, v))
}

// SentAtLTE applies the LTE predicate on the "sent_at" field.
func SentAtLTE(v time.Time) predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldLTE(FieldSentAt, v))
}

// SentAtIsNil applies the IsNil predicate on the "sent_at" field.
func SentAtIsNil() predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldIsNull(FieldSentAt))
}

// SentAtNotNil applies the NotNil predicate on the "sent_at" field.
func SentAtNotNil() predicate.NotificationLog {
	return predicate.NotificationLog(sql.FieldNotNull(FieldSentAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.NotificationLog) predicate.NotificationLog {
	return predicate.NotificationLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.NotificationLog) predicate.NotificationLog {
	return predicate.NotificationLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.NotificationLog) predicate.NotificationLog {
	return predicate.NotificationLog(sql.NotPredicates(p))
}
